In [4]:
import pandas as pd
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [8]:
PATH = '/content/drive/MyDrive/Observatorio SPVS/CU_Gasto Privado - Percepcion Seguridad/Percepcion de seguridad y convivencia.csv'
percepcion_df = pd.read_csv(PATH, dtype='str', sep=';')
percepcion_df.shape

(102522, 84)

In [ ]:
percepcion_df.columns

Index(['DIRECTORIO', 'NRO_ENCUESTA', 'SECUENCIA_ENCUESTA', 'SECUENCIA_P',
       'ORDEN', 'FEX_C', 'P3105', 'P1361S1', 'P1361S14', 'P1361S2', 'P1361S3',
       'P1361S4', 'P1361S5', 'P1361S6', 'P1361S7', 'P1361S11', 'P1361S8',
       'P1361S9', 'P1361S10', 'P1361S12', 'P1361S13', 'P3106', 'P3107',
       'P1358S1', 'P1358S13', 'P1358S2', 'P1358S3', 'P1358S4', 'P1358S5',
       'P1358S6', 'P1358S7', 'P1358S12', 'P1358S8', 'P1358S9', 'P1358S11',
       'P1358S10', 'P3108', 'P564', 'P3109S1', 'P3109S2', 'P3109S3', 'P3109S4',
       'P3109S5', 'P3109S6', 'P3109S7', 'P3109S8', 'P3109S9', 'P3109S10',
       'P3109S11', 'P3109S12', 'P3109S13', 'P3109S14', 'P3109S15', 'P3111S1',
       'P3111S2', 'P3111S3', 'P3111S4', 'P3111S5', 'P3111S6', 'P3111S7',
       'P3111S8', 'P3111S9', 'P3112S1', 'P3112S2', 'P3112S3', 'P3112S4',
       'P3112S5', 'P3112S6', 'P3112S7', 'P3112S8', 'P3112S9', 'P3112S10',
       'P3112S11', 'P3112S12', 'P3112S13', 'P3112S14', 'P3112S15', 'P1353S1',
       'P1353S2', 'P1353S3', 'P1353S4', 'P1353S5', 'P1353S6', 'P1115'],
      dtype='object')

In [ ]:
percepcion_df.head()

,DIRECTORIO,NRO_ENCUESTA,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P3105,P1361S1,P1361S14,P1361S2,...,P3112S13,P3112S14,P3112S15,P1353S1,P1353S2,P1353S3,P1353S4,P1353S5,P1353S6,P1115
0,501433,237,1,1,1,"108,419842080992",2,,,,...,,,,1,2,1,2,2,2,4
1,501433,237,2,1,2,"108,419842080992",2,,,,...,,,2,1,2,1,2,2,2,2
2,501434,237,1,1,1,"94,5309979723164",2,,,,...,,,,1,2,2,2,2,2,4
3,501434,237,2,1,2,"94,5309979723164",2,,,,...,,,2,2,2,1,2,2,2,2
4,501434,237,3,1,3,"94,5309979723164",2,,,,...,,,,1,2,2,2,2,2,2

In [10]:
percepcion_df.describe()

,DIRECTORIO,NRO_ENCUESTA,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P3105,P1361S1,P1361S14,P1361S2,...,P3112S13,P3112S14,P3112S15,P1353S1,P1353S2,P1353S3,P1353S4,P1353S5,P1353S6,P1115
count,102522,102522,102522,102522,102522,102522,102522,102522,102522,102522,...,102522,102522,102522,102522,102522,102522,102522,102522,102522,102522
unique,39791,1,18,7,17,14097,4,3,3,3,...,2,2,2,2,2,2,2,2,2,4
top,524920,237,1,1,1,"60,0703393744186",2,,,,...,,,,2,2,1,2,2,2,2
freq,14,102522,39791,101384,40368,320,72207,77570,77570,77570,...,82808,102319,64026,51442,84203,67051,98993,92063,76016,74674

In [9]:
Dict_columns = {
    'P3105': ' ',
    'P1361S1': ' ',
    'P1361S14': ' ',
    'P1361S2': ' ',
    'P1361S3': ' ',
    'P1361S4': ' ',
    'P1361S5': ' ',
    'P1361S6': ' ',
    'P1361S7': ' ',
    'P1361S11': ' ',
    'P1361S8': ' ',
    'P1361S9': ' ',
    'P1361S10': ' ',
    'P1361S12': ' ',
    'P1361S13': ' ',
    'P3106': ' ',
    'P3107',
    'P1358S1': ' ',
    'P1358S13': ' ',
    'P1358S2': ' ',
    'P1358S3': ' ',
    'P1358S4': ' ',
    'P1358S5',
    'P1358S6': ' ',
    'P1358S7': ' ',
    'P1358S12': ' ',
    'P1358S8': ' ',
    'P1358S9': ' ',
    'P1358S11',
    'P1358S10': ' ',
    'P3108': ' ',
    'P564': ' ',
    'P3109S1': ' ',
    'P3109S2': ' ',
    'P3109S3': ' ',
    'P3109S4',
    'P3109S5': ' ',
    'P3109S6': ' ',
    'P3109S7': ' ',
    'P3109S8': ' ',
    'P3109S9': ' ',
    'P3109S10',
    'P3109S11': ' ',
    'P3109S12': ' ',
    'P3109S13': ' ',
    'P3109S14': ' ',
    'P3109S15': ' ',
    'P3111S1',
    'P3111S2': ' ',
    'P3111S3': ' ',
    'P3111S4': ' ',
    'P3111S5': ' ',
    'P3111S6': ' ',
    'P3111S7',
    'P3111S8': ' ',
    'P3111S9': ' ',
    'P3112S1': ' ',
    'P3112S2': ' ',
    'P3112S3': ' ',
    'P3112S4',
    'P3112S5': ' ',
    'P3112S6': ' ',
    'P3112S7': ' ',
    'P3112S8': ' ',
    'P3112S9': ' ',
    'P3112S10',
    'P3112S11': ' ',
    'P3112S12': ' ',
    'P3112S13': ' ',
    'P3112S14': ' ',
    'P3112S15': ' ',
    'P1353S1',
    'P1353S2': ' ',
    'P1353S3': ' ',
    'P1353S4': ' ',
    'P1353S5': ' ',
    'P1353S6': ' ',
    'P1115': ' '
}

In [ ]:
{
    'P1398S1': ' ' ,
    'P1398S2': ' ' ,
    'P1398S3': ' ' ,
    'P1398S4': ' ' ,
    'P1398S5','P1398S6': ' ' ,
    'P1398S8': ' ' ,
    'P1398S9': ' ' ,
    'P1398S10': ' ' ,
    'P1398S12': ' ' ,
    'P1398S11',
    'P1398S13': ' ' ,
    'P1398S14': ' ' ,
    'P1398S15': ' ' ,
    'P1398S16': ' ' ,
    'P1398S17': ' ' ,
    'P1398S18',
    'P1398S19': ' ' ,
    'P1398S20': ' ' ,
    'P1590S1': ' ' ,
    'P1590S2': ' ' ,
    'P1590S3': ' ' ,
    'P1590S4',
    'P1590S5': ' ' ,
    'P520S1': ' ' ,
    'P520S2': ' ' ,
    'P520S3': ' ' ,
    'P520S4': ' ' ,
    'P520S8': ' ' ,
    'P520S9',
    'P520S5': ' ' ,
    'P520S10': ' ' ,
    'P520S6': ' ' ,
    'P520S11': ' ' ,
    'P520S7': ' ' ,
    'P3103': ' ' ,
    'P3104',
    'DEPMUNI': ' ' ,
    'CIUDADES28': ' ' , 
    'CLASE': ' ' ,
    'P1987': ' ' ,
    'P1988': ' ' ,
    'P1988S1': ' ' ,
    'P1989',
    'P1990': ' ' ,
    'P220': ' ' ,
    'P5785': ' ' ,
    'P5501': ' ' ,
    'P1402': ' ' ,
    'P1403': ' ' ,
    'P1365': ' ' ,
    'P1364',
    'P1363': ' ' ,
    'P6210': ' ' ,
    'P6210S1': ' ' ,
    'P1366': ' ' ,
    'P756': ' ' ,
    'P756S3': ' ' ,
    'P755',
    'P755S3': ' ' ,
    'P753': ' ' ,
    'P753S3': ' ' ,
    'P1662': ' ' ,
    'P6080': ' ' ,
    'P1906S1': ' ' ,
    'P1906S2',
    'P1906S3': ' ' ,
    'P1906S4': ' ' ,
    'P1906S5': ' ' ,
    'P1906S6': ' ' ,
    'P1906S7': ' ' ,
    'P1906S8',
    'P1906S9': ' ' ,
    'P3038': ' ' ,
    'P3039': ' ' ,
    '_merge'
}

# Archivo de Andrea

In [19]:
PATH = '/content/drive/MyDrive/Observatorio SPVS/CU_Gasto Privado - Percepcion Seguridad/ECSC2019(1) (1).csv'
percepcion_df = pd.read_csv(PATH, dtype='str', sep=',', encoding = 'latin-1')
percepcion_df.shape

(40368, 82)

In [20]:
percepcion_df.columns

Index(['DIRECTORIO', 'NRO_ENCUESTA', 'SECUENCIA_ENCUESTA', 'SECUENCIA_P',
       'ORDEN', 'FEX_C', 'P1398S1', 'P1398S2', 'P1398S3', 'P1398S4', 'P1398S5',
       'P1398S6', 'P1398S8', 'P1398S9', 'P1398S10', 'P1398S12', 'P1398S11',
       'P1398S13', 'P1398S14', 'P1398S15', 'P1398S16', 'P1398S17', 'P1398S18',
       'P1398S19', 'P1398S20', 'P1590S1', 'P1590S2', 'P1590S3', 'P1590S4',
       'P1590S5', 'P520S1', 'P520S2', 'P520S3', 'P520S4', 'P520S8', 'P520S9',
       'P520S5', 'P520S10', 'P520S6', 'P520S11', 'P520S7', 'P3103', 'P3104',
       'DEPMUNI', 'CIUDADES28', 'CLASE', 'P1987', 'P1988', 'P1988S1', 'P1989',
       'P1990', 'P220', 'P5785', 'P5501', 'P1402', 'P1403', 'P1365', 'P1364',
       'P1363', 'P6210', 'P6210S1', 'P1366', 'P756', 'P756S3', 'P755',
       'P755S3', 'P753', 'P753S3', 'P1662', 'P6080', 'P1906S1', 'P1906S2',
       'P1906S3', 'P1906S4', 'P1906S5', 'P1906S6', 'P1906S7', 'P1906S8',
       'P1906S9', 'P3038', 'P3039', '_merge'],
      dtype='object')

In [21]:
percepcion_df.head()

,DIRECTORIO,NRO_ENCUESTA,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P1398S1,P1398S2,P1398S3,P1398S4,...,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P1906S9,P3038,P3039,_merge
0,501433,236,1,1,1,108.4198421,Si,No,No,No,...,No puede hacerlo,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Mujeres,Hombre,Matched (3)
1,501434,236,1,1,1,94.53099797,No,No,No,No,...,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Otra,Mujer,Matched (3)
2,501435,236,1,1,1,93.78527306,Si,No,No,No,...,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Mujeres,Hombre,Matched (3)
3,501435,236,2,1,2,93.78527306,No,No,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Master only (1)
4,501436,236,1,1,1,91.99328026,No,No,No,No,...,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Sin dificultad,Otra,Mujer,Matched (3)

In [ ]:
percepcion_df.describe()

,DIRECTORIO,NRO_ENCUESTA,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P3105,P1361S1,P1361S14,P1361S2,...,P3112S13,P3112S14,P3112S15,P1353S1,P1353S2,P1353S3,P1353S4,P1353S5,P1353S6,P1115
count,102522,102522,102522,102522,102522,102522,102522,102522,102522,102522,...,102522,102522,102522,102522,102522,102522,102522,102522,102522,102522
unique,39791,1,18,7,17,14097,4,3,3,3,...,2,2,2,2,2,2,2,2,2,4
top,524920,237,1,1,1,"60,0703393744186",2,,,,...,,,,2,2,1,2,2,2,2
freq,14,102522,39791,101384,40368,320,72207,77570,77570,77570,...,82808,102319,64026,51442,84203,67051,98993,92063,76016,74674

In [23]:
percepcion_df.to_csv('/content/drive/MyDrive/Observatorio SPVS/CU_Gasto Privado - Percepcion Seguridad/ECSC2019(1).csv', encoding = 'utf-8')