# Introduccion

Este notebook contiene los procesos que se han realizado para acceder a las bases de datos del REGISTRO UNICO EMPRESARIAL para carturar información sobre las empresas (servicios y proveedores) y clientes de los contratos reportados en el sistema RENOVA de la SUPERINTENDENCIA DE VIGILANCIA Y SEGURIDAD RIVADA DE COLOMBIA. 

Contiene las funciones e scripts para cargar los datasets en Jupyter o Colab, a partir de archivos en formato CSV. 

Esta es la tercera etapa del trabajo con estos datos. 

Los objetivos de éste notebook son:
  - Identificar cuales son los sectores económicos a los que pertenecen las empresas que son servicios vigilados, proveedores de equipos, y clientes del sector de vigilancia y seguridad privada
  - Identificar la distribución de contratos en dichos sectores

Los datos de salida del notebook son:
  - Tablas con la proporción de empresas (Servicios y Clientes) en los diferentes sectores, bajo varias clasificaciones
  - Tablas con la proporción de contratos en los diferentes sectores, bajo varias clasificaciones
  (Tablas para copiar en Excel, para realizar informes)

In [ ]:
# First import the required libraries.
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns

# To load an manage files:
import io
import os

In [ ]:
# Ajustar No Maximo de Columnas para mostrar
# pd.get_option("display.max_columns")
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_columns', 20) # reset to default

In [ ]:
# Ajustar el tamaño máximo de columna que se muestra
#pd.get_option('display.max_colwidth')
#pd.set_option('display.max_colwidth', -1) 
#pd.set_option('display.max_colwidth', 50)  # reset to default

In [ ]:
# Ajustar el número máximo de filas para mostrar
#pd.get_option('display.max_rows')
pd.set_option('display.max_rows', None) # mostrar todas
#pd.set_option('display.max_rows', 60) # reset to default

In [ ]:
#para poder ver los montos en valores con todas las cifras significativas en vez de notación científica
pd.set_option('display.float_format',  '{:,.2f}'.format)

# Step 1: **Data Loading**

## Funciones Complementarias

#### Funcion para tener Nits de 14 caracteres

In [ ]:
# using strings of 14 characters lenght in order to match what we will get from the RUES database:
def extender_nit_string(nit):
    return (14-len(nit))*'0' + nit

# driver code
nit_list = ['1', '2', '3']
  
# Map method returns a map object
# so we cast it into list using list()
output_list = list(map(extender_nit_string, nit_list))
print(output_list)

['00000000000001', '00000000000002', '00000000000003']

## Load CSV into colab 
From Google Drive only (DO NOT RUN if in Jupyter):

In [ ]:
# For Using Google Drive, (Only if executing notebook from Google colab):
from google.colab import drive
drive.mount('/content/drive')

# after that:
# <--- Refresh mounted Drive
# <--- Look for file and get the path link

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Get the current directory
print(os.getcwd())
# Check if the directory exists
print(os.path.exists('../'))

/content
True

In [ ]:
ls

drive/  sample_data/

In [ ]:
cd /content/drive/MyDrive/Observatorio SPVS/

/content/drive/MyDrive/Observatorio SPVS

## Load files from OneDrive Folder

In [1]:
pwd

'd:\\DS4A\\SuperVigilancia\\OneDrive - Superintendencia de Vigilancia\\Proyecto Observatorio 2022\\6.Scripts\\3_CU_Gasto_Publico'

In [2]:
cd ../..

d:\DS4A\SuperVigilancia\OneDrive - Superintendencia de Vigilancia\Proyecto Observatorio 2022

In [ ]:
# Tabla de contratos en RENOVA  (de cliente gobierno)

PATH = 'BD RENOVA - Contratos cliente gobierno/contratos_gobierno_tipo_vigilado_Datos Validos.csv'
df_Gobierno = pd.read_csv(PATH, encoding = 'utf-8', dtype='str', sep=',' )
print(df_Gobierno.shape)
df_Gobierno.head()

(1792, 59)

In [ ]:
# Tabla de contratos reportados en RENOVA (de todos los clientes)

PATH = 'BD RENOVA - Contratos Todos los Clientes/contratos_sector_cliente_tipo_vigilado.csv'
df_Contratos = pd.read_csv(PATH, encoding = 'utf-8', dtype='str', sep=',' )
print(df_Contratos.shape)
df_Contratos.head()

,Unnamed: 0,ID_CONTRATO,FECHA_INICIO_CONTRATO,FECHA_FIN_CONTRATO,MONTO_CONTRATO,CANTIDAD_PUESTOS_CONTRATO,NIT_VIGILADO_x,DESCRIPCION_VALOR_AGREGADO,ID_ESTADO_CONTRATO,FECHA_CONTRATO_ESTADO,MAXDATE,MINDATE,ID_CLIENTE,TIPO_CONTRATO,ACTIVO_x,NUMERO_DOCUMENTO_CLIENTE,DIGITO_VERIFICACION,RAZON_SOCIAL_CLIENTE,PRIMER_NOMBRE_CLIENTE,SEGUNDO_NOMBRE_CLIENTE,PRIMER_APELLIDO_CLIENTE,SEGUNDO_APELIDO_CLIENTE,SECTOR_CLIENTE,CIIU_CLIENTE,DIRECCION_CLIENTE,TELEFONO_FIJO_CLIENTE,TELEFONO_MOVIL_CLIENTE,CORREO_ELECTRONICO_CLIENTE,CORREO_ELECTRONICO_ALTERNATIVO_CLIENTE,ID_CIUDAD,ID_DEPARTAMENTO,ID_DEPARTAMENTO1,ID_TIPO_DOCUMENTO_IDENTIFICACION,NUMERO_DOCUMENTO_REPRESENTANTE_LEGAL_CLIENTE,ID_TIPO_CLIENTE,TIPO_VIA,NOMBRE_NUM_VIA,PREFIJO_UNO,PREFIJO_UNO_UNO,NUMERO_VIA_GENERADORA,PREFIJO_DOS,PREFIJO_DOS_DOS,NUMERO_PLACA,COMPLEMENTARIO_LISTA,COMPLEMENTARIO_TEXTO,ID_TIPO_DOCUMENTO_IDENTIFICACION_REPRESENTANTE_LEGAL_CLIENTE,NIT_VIGILADO_y,CONSORCIO,ID_DIRECCION,ACTIVO_y,NIT_VIGILADO,ID_TIPO_SERVICIO,ID_TIPO_SOCIEDAD,RAZON_SOCIAL_VIGILADO,CIIU_VIGILADO
0,0,1,2011-08-02 00:00:00.000,2012-08-01 00:00:00.000,0.0,2.0,811001008,NaN,NaN,NaN,NaN,NaN,306,NaN,1,890920369,9,INDUSTRIAS EL TORO LTDA,RAFAEL,NaN,SANCHEZ,FRAN,1.0,1810,null null null null null null null null,2313506,0342313506,televigia@televigia.com,andicasta888@hotmail.com,5001.0,5.0,5.0,4,6783521,1,CARRERA,56,C,NaN,50.0,NaN,NaN,30.0,LOCAL,301,1.0,811001008,0.0,160029,1,811001008,2,2,TELEVIGIA,8020
1,1,3,2011-08-02 00:00:00.000,2012-08-01 00:00:00.000,37659.0,1.0,811001008,NaN,NaN,NaN,NaN,NaN,306,NaN,1,890920369,9,INDUSTRIAS EL TORO LTDA,RAFAEL,NaN,SANCHEZ,FRAN,1.0,1810,null null null null null null null null,2313506,0342313506,televigia@televigia.com,andicasta888@hotmail.com,5001.0,5.0,5.0,4,6783521,1,CARRERA,56,C,NaN,50.0,NaN,NaN,30.0,LOCAL,301,1.0,811001008,0.0,160029,1,811001008,2,2,TELEVIGIA,8020
2,2,4,2011-08-02 00:00:00.000,2012-08-01 00:00:00.000,177520.0,9.0,811001008,NaN,NaN,NaN,NaN,NaN,306,NaN,1,890920369,9,INDUSTRIAS EL TORO LTDA,RAFAEL,NaN,SANCHEZ,FRAN,1.0,1810,null null null null null null null null,2313506,0342313506,televigia@televigia.com,andicasta888@hotmail.com,5001.0,5.0,5.0,4,6783521,1,CARRERA,56,C,NaN,50.0,NaN,NaN,30.0,LOCAL,301,1.0,811001008,0.0,160029,1,811001008,2,2,TELEVIGIA,8020
3,3,6,2011-08-02 00:00:00.000,2012-08-01 00:00:00.000,37659.0,1.0,811001008,NaN,NaN,NaN,NaN,NaN,306,NaN,1,890920369,9,INDUSTRIAS EL TORO LTDA,RAFAEL,NaN,SANCHEZ,FRAN,1.0,1810,null null null null null null null null,2313506,0342313506,televigia@televigia.com,andicasta888@hotmail.com,5001.0,5.0,5.0,4,6783521,1,CARRERA,56,C,NaN,50.0,NaN,NaN,30.0,LOCAL,301,1.0,811001008,0.0,160029,1,811001008,2,2,TELEVIGIA,8020
4,4,8,2011-08-02 00:00:00.000,2012-08-01 00:00:00.000,37659.0,1.0,811001008,NaN,NaN,NaN,NaN,NaN,306,NaN,1,890920369,9,INDUSTRIAS EL TORO LTDA,RAFAEL,NaN,SANCHEZ,FRAN,1.0,1810,null null null null null null null null,2313506,0342313506,televigia@televigia.com,andicasta888@hotmail.com,5001.0,5.0,5.0,4,6783521,1,CARRERA,56,C,NaN,50.0,NaN,NaN,30.0,LOCAL,301,1.0,811001008,0.0,160029,1,811001008,2,2,TELEVIGIA,8020

In [ ]:
# Tabla de empresas registradas en el RUES

PATH = '/4.Bases_de_datos_Externas/Camaras_de_Comercio-Registro_Unico_de_Empresas_RUES/1.Clean_dataset/empresas_registradas_RUES.csv'
df_Gobierno = pd.read_csv(PATH, encoding = 'utf-8', dtype='str', sep=',' )
print(df_Gobierno.shape)
df_Gobierno.head()

(1792, 59)

# Step 2: Arreglar Formato y Consistencia de los datos

### Tabla de Contratos en RENOVA

In [ ]:
df_Contratos['NUMERO_DOCUMENTO_CLIENTE'].str[-1].head()

0    9
1    9
2    9
3    9
4    9
Name: NUMERO_DOCUMENTO_CLIENTE, dtype: object

In [ ]:
df_Contratos[df_Contratos['NUMERO_DOCUMENTO_CLIENTE'].str[-1] != df_Contratos['DIGITO_VERIFICACION']].shape

(167378, 55)

In [ ]:
print(len(df_Contratos['NUMERO_DOCUMENTO_CLIENTE']))
df_Contratos['NUMERO_DOCUMENTO_CLIENTE'].describe()

177614

count        177614
unique       102110
top       900581703
freq           3170
Name: NUMERO_DOCUMENTO_CLIENTE, dtype: object

In [ ]:
# Crear una lista de vigilados únicos
vigilado_list = pd.concat([df_Contratos['NIT_VIGILADO'], df_Contratos['NIT_VIGILADO_x'], df_Contratos['NIT_VIGILADO_y']]).unique()
vigilado_list =  list(map(extender_nit_string, vigilado_list))
len(vigilado_list)

720

In [ ]:
# Cuantas empresas son unicas?
len(set(vigilado_list))

720

In [ ]:
cliente_list = df_Contratos['NUMERO_DOCUMENTO_CLIENTE'].unique()
cliente_list =  list(map(extender_nit_string, cliente_list))
len(cliente_list)

102110

In [ ]:
# Cuantas empresas son unicas?
len(set(cliente_list))

102104

### Completar informacion de Tipos de Servicios y  Sectores de Cliente

In [ ]:
# mapeo de codigos de sectores

df_Contratos['TIPO_SERVICIO'] = df_Contratos['ID_TIPO_SERVICIO'].map({'1': 'Empresa de Vigilancia y Seguridad Privadas con Armas',
                                                '2': 'Empresa de Vigilancia y Seguridad Privadas sin Armas',
                                                '3': 'Cooperativa de Vigilancia y Seguridad Privada',
                                                '4': 'Empresa de Transporte de Valores',
                                                '5': 'Empresa Blindadora',
                                                '6': 'Empresa Arrendadora de Vehículos Blindados',
                                                '7': 'Empresa Asesora, Consultora e Investigadora en Vigilancia y Seguridad Privada',
                                                '8': 'Escuela de Capacitación y Entrenamiento en Vigilancia y Seguridad Privada' ,
                                                '9': 'Inscripción en el Registro de Fabricantes, Importadores, Comercializadores, Arrendadores e Instaladores de Equipos para la Vigilancia y la Seguridad Privada',
                                                '10': 'Servicio Comunitario de Vigilancia y Seguridad Privada',
                                                '11': 'Departamento de Seguridad Persona Natural',
                                                '12': 'Departamento de Seguridad Persona Jurídica'
                                               })
df_Contratos['TIPO_SERVICIO'].value_counts().to_frame()

                                                    TIPO_SERVICIO
Empresa de Vigilancia y Seguridad Privadas sin ...          75674
Empresa de Vigilancia y Seguridad Privadas con ...          70979
Empresa Arrendadora de Vehículos Blindados                  15840
Cooperativa de Vigilancia y Seguridad Privada                8566
Empresa Blindadora                                           3790
Empresa de Transporte de Valores                             1340
Inscripción en el Registro de Fabricantes, Impo...           1109
Empresa Asesora, Consultora e Investigadora en ...            315
Departamento de Seguridad Persona Jurídica                      1

In [ ]:
# mapeo de codigos de sectores

df_Contratos['SECTOR_CLIENTE_DESC'] = df_Contratos['SECTOR_CLIENTE'].map({'1.0': 'COMERCIAL',
                                                '2.0': 'FINANCIERO',
                                                '3.0': 'SERVICIOS',
                                                '4.0': 'INDUSTRIAL',
                                                '5.0': 'AGRICOLA Y GANADERO',
                                                '6.0': 'RESIDENCIAL',
                                                '7.0': 'GOBIERNO',
                                                '8.0': 'MINAS Y ENERGIA' ,
                                                '9.0': 'TRANSPORTES',
                                                '10.0': 'VIGILANCIA',
                                                '11.0': 'EDUCATIVO',
                                                '12.0': 'OTRO'
                                               })
df_Contratos['SECTOR_CLIENTE_DESC'].value_counts().to_frame()

                     SECTOR_CLIENTE_DESC
COMERCIAL                          38511
RESIDENCIAL                        18641
OTRO                               14223
SERVICIOS                           9207
VIGILANCIA                          6429
INDUSTRIAL                          4423
EDUCATIVO                           1909
GOBIERNO                            1818
TRANSPORTES                         1443
FINANCIERO                          1363
MINAS Y ENERGIA                      536
AGRICOLA Y GANADERO                  361

## Base de Datos de Empresas RENOVA

In [ ]:
# Tabla de Empresas en RENOVA

PATH = ''
df_Gobierno = pd.read_csv(PATH, encoding = 'utf-8', dtype='str', sep=',' )
df_Gobierno.shape

In [ ]:
# Crear una lista de vigilados únicos
vigilado_list = pd.concat([df_Contratos['NIT_VIGILADO'], df_Contratos['NIT_VIGILADO_x'], df_Contratos['NIT_VIGILADO_y']]).unique()
vigilado_list =  list(map(extender_nit_string, vigilado_list))
len(vigilado_list)

720

In [ ]:
# Cuantas empresas son unicas?
len(set(vigilado_list))

720

In [ ]:
cliente_list = df_Contratos['NUMERO_DOCUMENTO_CLIENTE'].unique()
cliente_list =  list(map(extender_nit_string, cliente_list))
len(cliente_list)

102110

In [ ]:
# Cuantas empresas son unicas?
len(set(cliente_list))

102104

## Base de datos de registro de empresas en RUES

In [ ]:
empresas_RUES_df = pd.read_csv('empresas_registradas_RUES.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (6,9,10,11) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
# Tenemos 5 millones de empresas
empresas_RUES_df.shape

(5521230, 12)

# Step 2: Buscar empresas registradas en el RUES

In [ ]:
vigilados_df[vigilados_df['numero_identificacion']!=vigilados_df['nit_propietario'].str[5:]][['numero_identificacion', 'nit_propietario']].head()

(3080645, 12)
(2440585, 12)

   numero_identificacion nit_propietario
4               37896777             nan
10             900116408             nan
11              52635635             nan
26            1067402410             nan
29         0000000000000             nan
31              37220512             nan
32              12962175             nan
33              41619240             nan
37              14221605             nan
39            1049618609             nan
40             901194230             nan
41              14230417             nan
44              91233400             nan
47            1130636655             nan
50              52950007             nan
52             900702353             nan
54         0000000000000             nan
60         0000000000000             nan
62              77015401             nan
65               5884216             nan

In [ ]:
# Test con un nit
empresas_RUES_df.loc[empresas_RUES_df['nit_propietario'].str.contains(nit) == True ]

,Unnamed: 0,camara_comercio,razon_social,estado_matricula,ultimo_ano_renovado,cod_ciiu_act_econ_pri,codigo_clase_identificacion,clase_identificacion,numero_identificacion,nit_propietario,digito_verificacion,cod_ciiu_act_econ_sec
395852,395852,MANIZALES,SEGURTRONIC LTDA,CANCELADA,"2,018.00",8020,2.00,NIT,800250741,00000800250741,3,4774
794869,794869,MEDELLIN PARA ANTIOQUIA,SEGURTRONIC LIMITADA,ACTIVA,"2,022.00",8020,2.00,NIT,800250741,00000800250741,3,8010
1071479,1071479,SANTA MARTA,SOGERCOL SAS,CANCELADA,"2,017.00",8121,2.00,NIT,800250741,00000800250741,3,NaN
1082306,1082306,SANTA MARTA,SEGURTRONIC LTDA,ACTIVA,"2,022.00",8020,2.00,NIT,800250741,00000800250741,3,NaN
1125387,1125387,BUCARAMANGA,SEGURTRONIC LTDA,CANCELADA,"2,018.00",8020,2.00,NIT,800250741,00000800250741,3,4774
1424280,1424280,BOGOTA,SEGURTRONIC LTDA,CANCELADA,"2,018.00",8020,2.00,NIT,800250741,00000800250741,3,4774
2053788,2053788,ORIENTE ANTIOQUENO,AGENCIA SEGURTRONIC RIONEGRO,ACTIVA,"2,022.00",8020,2.00,NIT,800250741,00000800250741,3,NaN
2858598,2858598,MONTERIA,SEGURTRONIC MONTERIA,CANCELADA,"2,018.00",8020,2.00,NIT,800250741,00000800250741,3,4774
4167740,4167740,BARRANQUILLA,SEGURTRONIC LTDA.,CANCELADA,"2,019.00",8020,2.00,NIT,800250741,00000800250741,3,4774
4393070,4393070,MEDELLIN PARA ANTIOQUIA,SEGURIDAD ELECTRONICA SEGURTRONIC,CANCELADA,"2,005.00",7492,2.00,NIT,800250741,00000800250741,3,NaN
5430469,5430469,CARTAGENA,SEGURTRONIC,ACTIVA,"2,022.00",8020,2.00,NIT,800250741,00000800250741,3.00,NaN

In [ ]:
# Test con un nit
empresas_RUES_df.loc[empresas_RUES_df['nit_propietario'].str.contains('800233036') == True ]

,Unnamed: 0,camara_comercio,razon_social,estado_matricula,ultimo_ano_renovado,cod_ciiu_act_econ_pri,codigo_clase_identificacion,clase_identificacion,numero_identificacion,nit_propietario,digito_verificacion,cod_ciiu_act_econ_sec
226300,226300,CALI,METRO ALARMAS LTDA VALLE,CANCELADA,"2,019.00",8020,2.00,NIT,800233036,00000800233036,7,NaN
689954,689954,ORIENTE ANTIOQUENO,METRO ALARMAS RIONEGRO,CANCELADA,"2,019.00",8020,2.00,NIT,800233036,00000800233036,7,4652
1425022,1425022,CALI,METRO ALARMAS LTDA,CANCELADA,"2,002.00",5169,2.00,NIT,800233036,00000800233036,7,NaN
4148531,4148531,MEDELLIN PARA ANTIOQUIA,R&R INVERTERRA,ACTIVA,"2,022.00",6810,2.00,NIT,800233036,00000800233036,7,7010
4613978,4613978,MEDELLIN PARA ANTIOQUIA,METROVIGIAS,CANCELADA,"2,013.00",8010,2.00,NIT,800233036,00000800233036,7,NaN
4630769,4630769,BOGOTA,METRO ALARMAS LTDA,CANCELADA,"2,019.00",8020,2.00,NIT,800233036,00000800233036,7,NaN
4672935,4672935,PEREIRA,METRO ALARMAS LTDA.,CANCELADA,"2,019.00",8020,2.00,NIT,800233036,00000800233036,7,4652
5189653,5189653,BARRANQUILLA,METRO ALARMAS LTDA.,CANCELADA,"2,019.00",8020,2.00,NIT,800233036,00000800233036,7.00,4652

In [ ]:
# [WARNING] Este código es muy demorado, en los 10 primeros registros se demoro 10 minutos.
'''
# Cuantos Vigilados están en el RUES?
count = 0
for nit in vigilado_list:
    count = count + empresas_RUES_df['nit_propietario'].str.contains(nit).sum()
    #print (count)
print ('vigilados en el RUES: ', count)


# Cuantos Clientes están en el RUES?
count = 0
for nit in cliente_list:
    count = count + empresas_RUES_df['nit_propietario'].str.contains(nit).sum()
print ('Clientes en el RUES: ', count)
'''

"\n# Cuantos Vigilados están en el RUES?\ncount = 0\nfor nit in vigilado_list:\n    count = count + empresas_RUES_df['nit_propietario'].str.contains(nit).sum()\n    #print (count)\nprint ('vigilados en el RUES: ', count)\n\n\n# Cuantos Clientes están en el RUES?\ncount = 0\nfor nit in cliente_list:\n    count = count + empresas_RUES_df['nit_propietario'].str.contains(nit).sum()\nprint ('Clientes en el RUES: ', count)\n"

In [ ]:
# Buscar los vigilados que están en el RUES usando pandas:

empresas_RUES_df['nit_propietario'].isin(vigilado_list).sum()

2315

In [ ]:
vigilados_df = empresas_RUES_df.loc[empresas_RUES_df['nit_propietario'].isin(vigilado_list) == True ]
vigilados_df.sort_values(by=['nit_propietario', 'camara_comercio'], inplace = True)
#vigilados_df.drop_duplicates(subset=['camara_comercio', 'razon_social', 'nit_propietario'], keep='first', inplace=True, ignore_index=True)
vigilados_df.shape

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

(2315, 12)

In [ ]:
# Se puede usar el nit como indice? NO, porque está repetido
#vigilados_df.set_index('nit_propietario', drop=True,  inplace=True, verify_integrity=True)

In [ ]:
len(vigilados_df['nit_propietario'].unique())

478

In [ ]:
vigilados_df['cod_ciiu_act_econ_pri'].value_counts().head(20)

8010    1977
5611      92
4923      56
8020      49
9999      20
7492      18
4659      15
1040       8
8030       8
7710       7
4719       5
2930       5
9609       4
5619       3
6190       3
2920       2
8110       2
5241       2
4921       2
4690       2
Name: cod_ciiu_act_econ_pri, dtype: int64

In [ ]:
vigilados_df['cod_ciiu_act_econ_sec'].value_counts().head(20)

8020    1059
1040      80
8010      57
8299      25
5229      14
6190      12
7730      11
4923      10
8030      10
4774       9
5611       6
7710       6
6201       5
4659       5
4690       4
3313       4
7490       4
4652       4
6810       4
4321       3
Name: cod_ciiu_act_econ_sec, dtype: int64

In [ ]:
# Buscar los Clientes que están en el RUES usando pandas:

empresas_RUES_df['nit_propietario'].isin(cliente_list).sum()

444920

In [ ]:
clientes_df = empresas_RUES_df.loc[empresas_RUES_df['nit_propietario'].isin(cliente_list) == True ]
clientes_df.sort_values(by=['numero_identificacion', 'camara_comercio'], inplace = True)
clientes_df.drop_duplicates(subset=['camara_comercio', 'razon_social', 'nit_propietario'], keep='first', inplace=True, ignore_index=True)
clientes_df.shape

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

(426019, 12)

In [ ]:
len(clientes_df['nit_propietario'].unique())

44739

In [ ]:
clientes_df.head()

,Unnamed: 0,camara_comercio,razon_social,estado_matricula,ultimo_ano_renovado,cod_ciiu_act_econ_pri,codigo_clase_identificacion,clase_identificacion,numero_identificacion,nit_propietario,digito_verificacion,cod_ciiu_act_econ_sec
0,3888483,PASTO,SIGLO XXI ENGLISH CENTER,CANCELADA,"2,008.00",8060,6.00,SIN IDENTIFICACION,0,00000000000000,NaN,NaN
1,4810271,TULUA,RECICLAJE Y ASEO ZARZAL EMPRESA ASOCIATIVA DE ...,MATRÍCULA CANCELADA LEY 1429,"1,998.00",4665,2.00,NIT,0,00000000000000,NaN,NaN
2,150,ABURRA SUR,TIENDA LAKSHMI,CANCELADA,"1,994.00",9999,6.00,SIN IDENTIFICACION,0000000000000,00000000000000,NaN,NaN
3,1831,ABURRA SUR,SHUJO ESCOVAR CARDONA,CANCELADA,"1,995.00",9999,6.00,SIN IDENTIFICACION,0000000000000,00000000000000,NaN,NaN
4,2855,ABURRA SUR,ELASTOQUIMICA LTDA.,CANCELADA,"1,992.00",9999,6.00,SIN IDENTIFICACION,0000000000000,00000000000000,NaN,NaN

In [ ]:
clientes_df['cod_ciiu_act_econ_pri'].value_counts().head(20)

9999    137234
4711     13079
4771     12182
4773     11780
5611      9650
9200      8767
4719      6590
6412      5568
1410      5087
4772      4813
4752      4637
4754      4464
4923      4210
4530      4140
8621      3758
4759      3738
5630      3403
8299      3224
9602      3206
1081      3169
Name: cod_ciiu_act_econ_pri, dtype: int64

In [ ]:
clientes_df['cod_ciiu_act_econ_sec'].value_counts().head(20)

8299    3900
4711    3843
4741    2678
5310    2164
4771    1881
6810    1874
4772    1739
4773    1646
4732    1522
5320    1437
6190    1394
8699    1380
5611    1153
4719    1150
4530    1121
4759    1059
4923     976
5630     963
4520     923
8621     922
Name: cod_ciiu_act_econ_sec, dtype: int64

## CODIGO ABANDONADO Base de Datos de Códigos CIIU 

Se consultaron los archivos Tablas Correlativas en:

Sistema Estadístico Nacional (SEN)/ Normas y estándaresNomenclaturas y clasificaciones / Tablas Correlativas

https://www.dane.gov.co/index.php/sistema-estadistico-nacional-sen/normas-y-estandares/nomenclaturas-y-clasificaciones/tablas-correlativas

Y se extraen los Códigos CIUU que vienen por División, Grupo y Clase

In [ ]:
# No fue posible cargar el archivo anidado de códigos CIIU en JSON.
#import json
#with open ("../CIIU.json", "r", encoding='utf-8') as file:
    #ciiu_dict = pd.DataFrame.from_dict(json.load(file), orient-'columns')
    #data=file.read().lower()
    #ciiu_dict = json.load(file)
    #ciiu_dict = pd.read_json(file, encoding='utf-8')
    #ciiu_dict = pd.json_normalize(data)
    #ciiu_dict = pd.DataFrame(data)
#ciiu_dict.head()

In [ ]:
ls

 Volume in drive D has no label.
 Volume Serial Number is 5E36-13E0

 Directory of d:\DS4A\SuperVigilancia\OneDrive - Superintendencia de Vigilancia\Proyecto Observatorio 2022\4.Bases_de_datos_Externas\Camaras_de_Comercio-Registro_Unico_de_Empresas_RUES

10/13/2022  05:29 PM    <DIR>          .
10/13/2022  05:29 PM    <DIR>          ..
10/10/2022  04:50 PM    <DIR>          0.Raw_dataset
10/11/2022  06:03 PM    <DIR>          1.Clean_dataset
10/10/2022  04:49 PM    <DIR>          2.Processed_dataset
10/13/2022  04:22 PM            81,736 actividades_codigo_ciiu_2021.xlsx
10/13/2022  04:30 PM            95,972 CIIU.json
10/13/2022  04:14 PM            56,815 CIIU.txt
09/20/2022  07:43 PM            70,594 Tabla correlativa CIIU 4 A.C. (2020) - CIIU 4 A.C. (2021).xlsx
10/13/2022  05:27 PM           113,758 Tabla correlativa CIIU.xlsx
09/21/2022  10:51 AM           226,127 TC_CIIU4AC2020-CIIU4AC2021.xlsx
               6 File(s)        645,002 bytes
               5 Dir(s)  387,700,080,640 bytes free

In [ ]:
# Tabla de Divisiónes de Códigos CIUU del DANE:
PATH = 'Tabla correlativa CIIU 4 A.C. (2020) - CIIU 4 A.C. (2021).xlsx'
CIIU_codes_df = pd.read_excel(PATH,  sheet_name='Clase') # encoding = 'utf-8', dtype='str', sep=',' ) #
CIIU_codes_df.shape

In [ ]:
CIIU_grupo_codes_dict = CIIU_grupo_codes_df['Descripcion'].to_dict()

In [ ]:
CIIU_codes_df['Code Division'] = CIIU_codes_df[' División'].str.replace('DIVISIÓN ', '').astype(str)

CIIU_codes_df['Code Division'].head()

0    01
1    02
2    03
3    05
4    06
Name: Code Division, dtype: object

:

:

In [ ]:
CIIU_codes_df.set_index('Code Division', drop=True,  inplace=True, verify_integrity=True)

:

:

In [ ]:
CIIU_codes_df['División_Desc'].head()

Code Division
01    Agricultura, ganadería, caza y actividades de ...
02                  Silvicultura y extracción de madera
03                                  Pesca y acuicultura
05             Extracción de carbón de piedra y lignito
06           Extracción de petróleo crudo y gas natural
Name: División_Desc, dtype: object

:

:

In [ ]:
# Crear un diccionario de codigos a descipciones de divisiones
#CIIU_codes_df['Code Division'] = CIIU_codes_df['Code Division']
CIIU_codes_dict = CIIU_codes_df['División_Desc'].to_dict()
CIIU_codes_dict

{'01': 'Agricultura, ganadería, caza y actividades de servicios conexas',
 '02': 'Silvicultura y extracción de madera',
 '03': 'Pesca y acuicultura',
 '05': 'Extracción de carbón de piedra y lignito',
 '06': 'Extracción de petróleo crudo y gas natural',
 '07': 'Extracción de minerales metalíferos',
 '08': 'Extracción de otras minas y canteras',
 '09': 'Actividades de servicios de apoyo para la explotación de minas y canteras',
 '10': 'Elaboración de productos alimenticios',
 '11': 'Elaboración de bebidas',
 '12': 'Elaboración de productos de tabaco',
 '13': 'Fabricación de productos textiles',
 '14': 'Confección de prendas de vestir',
 '15': 'Curtido y recurtido de cueros; fabricación de calzado; fabricación de artículos de viaje, maletas, bolsos de mano y artículos similares, y fabricación de artículos de talabartería y guarnicionería; adobo y teñido de pieles',
 '16': 'Transformación de la madera y fabricación de productos de madera y de corcho, excepto muebles; fabricación de artículos de cestería y espartería',
 '17': 'Fabricación de papel, cartón y productos de papel y cartón',
 '18': 'Actividades de impresión y de producción de copias a partir de grabaciones originales',
 '19': 'Coquización, fabricación de productos de la refinación del petróleo y actividad de mezcla de combustibles',
 '20': 'Fabricación de sustancias y productos químicos',
 '21': 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico',
 '22': 'Fabricación de productos de caucho y de plástico',
 '23': 'Fabricación de otros productos minerales no metálicos',
 '24': 'Fabricación de productos metalúrgicos básicos',
 '25': 'Fabricación de productos elaborados de metal, excepto maquinaria y equipo',
 '26': 'Fabricación de productos informáticos, electrónicos y ópticos',
 '27': 'Fabricación de aparatos y equipo eléctrico',
 '28': 'Fabricación de maquinaria y equipo n.c.p.',
 '29': 'Fabricación de vehículos automotores, remolques y semirremolques',
 '30': 'Fabricación de otros tipos de equipo de transporte',
 '31': 'Fabricación de muebles, colchones y somieres',
 '32': 'Otras industrias manufactureras',
 '33': 'Instalación, mantenimiento y reparación especializado de maquinaria y equipo',
 '35': 'Suministro de electricidad, gas, vapor y aire acondicionado',
 '36': 'Captación, tratamiento y distribución de agua',
 '37': 'Evacuación y tratamiento de aguas residuales',
 '38': 'Recolección, tratamiento y disposición de desechos, recuperación de materiales',
 '39': 'Actividades de saneamiento ambiental y otros servicios de gestión de desechos',
 '41': 'Construcción de edificios',
 '42': 'Obras de ingeniería civil',
 '43': 'Actividades especializadas para la construcción de edificios y obras de ingeniería civil',
 '45': 'Comercio, mantenimiento y reparación de vehículos automotores y motocicletas, sus partes, piezas y accesorios',
 '46': 'Comercio al por mayor y en comisión o por contrata, excepto el comercio de vehículos automotores y motocicletas',
 '47': 'Comercio al por menor (incluso el comercio al por menor de combustibles), excepto el de vehículos automotores y motocicletas',
 '49': 'Transporte terrestre; transporte por tuberías',
 '50': 'Transporte acuático',
 '51': 'Transporte aéreo',
 '52': 'Almacenamiento y actividades complementarias al transporte',
 '53': 'Correo y servicios de mensajería',
 '55': 'Alojamiento',
 '56': 'Actividades de servicios de comidas y bebidas',
 '58': 'Actividades de edición',
 '59': 'Actividades cinematográficas, de video y producción de programas de televisión, grabación de sonido y edición de música',
 '60': 'Actividades de programación, transmisión y/o difusión',
 '61': 'Telecomunicaciones',
 '62': 'Desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas), consultoría informática y actividades relacionadas',
 '63': 'Actividades de servicios de información',
 '64': 'Actividades de servicios financieros, excepto las de seguros y de pensiones',
 '65': 'Seguros (incluso el reaseguro), seguros sociales y fondos de pensiones, excepto la seguridad social',
 '66': 'Actividades auxiliares de las actividades de servicios financieros',
 '67': 'Actividades de servicios financieros, cambiarias, de seguros y de pensiones',
 '68': 'Actividades inmobiliarias',
 '69': 'Actividades jurídicas y de contabilidad',
 '70': 'Actividades de administración empresarial; actividades de consultoría de gestión',
 '71': 'Actividades de arquitectura e ingeniería; ensayos y análisis técnicos',
 '72': 'Investigación científica y desarrollo',
 '73': 'Publicidad y estudios de mercado',
 '74': 'Otras actividades profesionales, científicas y técnicas',
 '75': 'Actividades veterinarias',
 '77': 'Actividades de alquiler y arrendamiento',
 '78': 'Actividades de empleo',
 '79': 'Actividades de las agencias de viajes, operadores turísticos, servicios de reserva y actividades relacionadas',
 '80': 'Actividades de seguridad e investigación privada',
 '81': 'Actividades de servicios a edificios y paisajismo (jardines, zonas verdes)',
 '82': 'Actividades administrativas y de apoyo de oficina y otras actividades de apoyo a las empresas',
 '84': 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria',
 '85': 'Educación',
 '86': 'Actividades de atención de la salud humana',
 '87': 'Actividades de atención residencial medicalizada',
 '88': 'Actividades de asistencia social sin alojamiento',
 '90': 'Actividades creativas, artísticas y de entretenimiento',
 '91': 'Actividades de bibliotecas, archivos, museos y otras actividades culturales',
 '92': 'Actividades de juegos de azar y apuestas',
 '93': 'Actividades deportivas y actividades recreativas y de esparcimiento',
 '94': 'Actividades de asociaciones',
 '95': 'Mantenimiento y reparación de computadores, efectos personales y enseres domésticos',
 '96': 'Otras actividades de servicios personales',
 '97': 'Actividades de los hogares individuales como empleadores de personal doméstico',
 '98': 'Actividades no diferenciadas de los hogares individuales como productores de bienes y servicios para uso propio',
 '99': 'Actividades de organizaciones y entidades extraterritoriales'}

:

:

In [ ]:
CIIU_codes_df[['Seccion', 'Seccion_Desc']].head()

                 Seccion                                       Seccion_Desc
Code Division
01             SECCIÓN A  AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y P...
02             SECCIÓN A  AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y P...
03             SECCIÓN A  AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y P...
05             SECCIÓN B                    EXPLOTACIÓN DE MINAS Y CANTERAS
06             SECCIÓN B                    EXPLOTACIÓN DE MINAS Y CANTERAS

:

:

In [ ]:
# Crear un diccionario de codigos a descipciones de secciones (Sectores?)
CIIU_seccion_dict = CIIU_codes_df['Seccion_Desc'].to_dict()

:

:

In [ ]:
# Tabla de Grupos de Códigos CIUU del DANE:

PATH = '/content/drive/MyDrive/Observatorio SPVS/BD RENOVA - Contratos Todos los Clientes/Tabla correlativa CIIU 4 A.C. (2020) - CIIU 4 A.C. (2021).xlsx'
CIIU_grupo_codes_df = pd.read_excel(PATH,  sheet_name='Grupo') # encoding = 'utf-8', dtype='str', sep=',' ) #
CIIU_grupo_codes_df.shape

(246, 2)

:

:

In [ ]:
CIIU_grupo_codes_df.head()

   Grupo                                        Descripcion
0     11                    Cultivos agrícolas transitorios
1     12                     Cultivos agrícolas permanentes
2     13  Propagación de plantas (actividades de los viv...
3     14                                          Ganadería
4     15            Explotación mixta (agrícola y pecuaria)

:

:

In [ ]:
CIIU_grupo_codes_df['Grupo'] = CIIU_grupo_codes_df['Grupo'].astype(int).astype(str)
CIIU_grupo_codes_df['Grupo'].head()

0    11
1    12
2    13
3    14
4    15
Name: Grupo, dtype: object

:

:

In [ ]:
CIIU_grupo_codes_df.set_index('Grupo', drop=True,  inplace=True, verify_integrity=True)

:

:

In [ ]:
CIIU_grupo_codes_df['Descripcion'].tail()

Grupo
960            Otras actividades de servicios personales
970    Actividades de los hogares individuales como e...
981    Actividades no diferenciadas de los hogares in...
982    Actividades no diferenciadas de los hogares in...
990    Actividades de organizaciones y entidades extr...
Name: Descripcion, dtype: object

:

:

# Step 3: Asignar descripciones de los códigos a cada vigilado y cada cliente

en las dos tablas de Vigilados registrados y Clientes registrados

### Por División

In [ ]:
# dos nuevas columnas con la División de los códigos CIUU en cada tabla (vigilados y clientes)
vigilados_df['ciuu_division_pri'] = vigilados_df['cod_ciiu_act_econ_pri'].str[:2]
vigilados_df['ciuu_division_sec'] = vigilados_df['cod_ciiu_act_econ_sec'].str[:2]
clientes_df['ciuu_division_pri'] = clientes_df['cod_ciiu_act_econ_pri'].str[:2]
clientes_df['ciuu_division_sec'] = clientes_df['cod_ciiu_act_econ_sec'].str[:2]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
#Incluir dos nuevas columnas con las descripciones de los códigos CIUU en cada tabla (Vigilados y Clientes)
vigilados_df['ciuu_division_pri_desc'] = vigilados_df['ciuu_division_pri'].map(CIIU_codes_dict)
vigilados_df['ciuu_division_sec_desc'] = vigilados_df['ciuu_division_sec'].map(CIIU_codes_dict)
clientes_df['ciuu_division_pri_desc'] = clientes_df['ciuu_division_pri'].map(CIIU_codes_dict)
clientes_df['ciuu_division_sec_desc'] = clientes_df['ciuu_division_sec'].map(CIIU_codes_dict)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

# Estadísticas de las actividades económicas de los Vigilados y los Clientes

In [ ]:
vigilados_df[['ciuu_division_pri','ciuu_division_pri_desc']].value_counts().head().to_frame()

                                                                         0
ciuu_division_pri ciuu_division_pri_desc
80                Actividades de seguridad e investigación privada    2034
56                Actividades de servicios de comidas y bebidas         95
49                Transporte terrestre; transporte por tuberías         58
74                Otras actividades profesionales, científicas y ...    21
99                Actividades de organizaciones y entidades extra...    20

In [ ]:
vigilados_df[['ciuu_division_sec','ciuu_division_sec_desc']].value_counts().head().to_frame()

                                                                         0
ciuu_division_sec ciuu_division_sec_desc
80                Actividades de seguridad e investigación privada    1126
10                Elaboración de productos alimenticios                 80
82                Actividades administrativas y de apoyo de ofici...    25
77                Actividades de alquiler y arrendamiento               17
47                Comercio al por menor (incluso el comercio al p...    16

In [ ]:
clientes_df[['ciuu_division_pri', 'ciuu_division_pri_desc']].value_counts().head().to_frame()

                                                                          0
ciuu_division_pri ciuu_division_pri_desc
47                Comercio al por menor (incluso el comercio al p...  27967
46                Comercio al por mayor y en comisión o por contr...   6978
92                Actividades de juegos de azar y apuestas             5700
64                Actividades de servicios financieros, excepto l...   5470
56                Actividades de servicios de comidas y bebidas        4811

In [ ]:
clientes_df[['ciuu_division_sec','ciuu_division_sec_desc']].value_counts().head().to_frame()

                                                                          0
ciuu_division_sec ciuu_division_sec_desc
47                Comercio al por menor (incluso el comercio al p...  14034
46                Comercio al por mayor y en comisión o por contr...   4722
82                Actividades administrativas y de apoyo de ofici...   3416
53                Correo y servicios de mensajería                     2506
56                Actividades de servicios de comidas y bebidas        2372

### Por Clase CIIU

In [ ]:
# dos nuevas columnas con la División de los códigos CIUU en cada tabla (vigilados y clientes)
vigilados_df['ciuu_grupo_pri'] = vigilados_df['cod_ciiu_act_econ_pri'].str[:3]
vigilados_df['ciuu_grupo_sec'] = vigilados_df['cod_ciiu_act_econ_sec'].str[:3]
clientes_df['ciuu_grupo_pri'] = clientes_df['cod_ciiu_act_econ_pri'].str[:3]
clientes_df['ciuu_grupo_sec'] = clientes_df['cod_ciiu_act_econ_sec'].str[:3]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
#Incluir dos nuevas columnas con las descripciones de los códigos CIUU en cada tabla (Vigilados y Clientes)
vigilados_df['ciuu_grupo_pri_desc'] = vigilados_df['ciuu_grupo_pri'].map(CIIU_grupo_codes_dict)
vigilados_df['ciuu_grupo_sec_desc'] = vigilados_df['ciuu_grupo_sec'].map(CIIU_grupo_codes_dict)
clientes_df['ciuu_grupo_pri_desc'] = clientes_df['ciuu_grupo_pri'].map(CIIU_grupo_codes_dict)
clientes_df['ciuu_grupo_sec_desc'] = clientes_df['ciuu_grupo_sec'].map(CIIU_grupo_codes_dict)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
vigilados_df[['ciuu_grupo_pri','ciuu_grupo_pri_desc']].value_counts().head().to_frame()

                                                                      0
ciuu_grupo_pri ciuu_grupo_pri_desc
801            Actividades de seguridad privada                    1977
561            Actividades de restaurantes, cafeterías y servi...    95
492            Transporte terrestre público automotor                58
802            Actividades de servicios de sistemas de seguridad     49
749            Otras actividades profesionales, científicas y ...    21

In [ ]:
vigilados_df[['ciuu_grupo_sec', 'ciuu_grupo_sec_desc']].value_counts().head().to_frame()

                                                                      0
ciuu_grupo_sec ciuu_grupo_sec_desc
802            Actividades de servicios de sistemas de seguridad   1059
104            Elaboración de productos lácteos                      80
801            Actividades de seguridad privada                      57
829            Actividades de servicios de apoyo a las empresa...    25
522            Actividades de las estaciones, vías y servicios...    14

In [ ]:
clientes_df[['ciuu_grupo_pri','ciuu_grupo_pri_desc']].value_counts().shape

(207,)

In [ ]:
clientes_df[['ciuu_grupo_pri','ciuu_grupo_pri_desc']].value_counts().head()

ciuu_grupo_pri  ciuu_grupo_pri_desc
477             Comercio al por menor de otros productos en establecimientos especializados    13723
920             Actividades de juegos de azar y apuestas                                        5700
471             Comercio al por menor en establecimientos no especializados                     5641
561             Actividades de restaurantes, cafeterías y servicio móvil de comidas             4428
641             Intermediación monetaria                                                        4151
dtype: int64

In [ ]:
clientes_df[['ciuu_grupo_sec','ciuu_grupo_sec_desc']].value_counts().head(10)

ciuu_grupo_sec  ciuu_grupo_sec_desc
471             Comercio al por menor en establecimientos no especializados                                                      3893
477             Comercio al por menor de otros productos en establecimientos especializados                                      3546
829             Actividades de servicios de apoyo a las empresas n.c.p.                                                          3209
474             Comercio al por menor de equipos de informática y de comunicaciones en establecimientos especializados           1738
561             Actividades de restaurantes, cafeterías y servicio móvil de comidas                                              1726
472             Comercio al por menor de alimentos (víveres en general), bebidas y tabaco, en establecimientos especializados    1672
531             Actividades postales nacionales                                                                                  1521
681             Actividades inmobiliarias realizadas con bienes propios o arrendados                                             1500
464             Comercio al por mayor de artículos y enseres domésticos (incluidas prendas de vestir)                            1499
869             Otras actividades de atención relacionadas con la salud humana                                                   1471
dtype: int64

### Por ciudades

In [ ]:
vigilados_df['camara_comercio'].value_counts().head().to_frame()

                         camara_comercio
BOGOTA                               308
CALI                                 177
MEDELLIN PARA ANTIOQUIA              158
BUCARAMANGA                          140
BARRANQUILLA                         133

In [ ]:
clientes_df['camara_comercio'].value_counts().head()

BOGOTA                     18931
MEDELLIN PARA ANTIOQUIA    11663
CALI                        7276
BARRANQUILLA                4977
BUCARAMANGA                 4189
Name: camara_comercio, dtype: int64

### Por Seccion CIIU

In [ ]:
#Incluir una columna con el sector del cliente:

vigilados_df['ciuu_seccion_desc'] = vigilados_df['ciuu_division_pri'].map(CIIU_seccion_dict)
clientes_df['ciuu_seccion_desc'] = clientes_df['ciuu_division_pri'].map(CIIU_seccion_dict)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
vigilados_df['ciuu_seccion_desc'].value_counts().head().to_frame()

                                                    ciuu_seccion_desc
ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE A...               2048
ALOJAMIENTO Y SERVICIOS DE COMIDA                                  96
TRANSPORTE Y ALMACENAMIENTO                                        63
COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓ...                 31
ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS                  22

In [ ]:
ciudades_vigilados = vigilados_df['camara_comercio'].value_counts().head(10).keys().to_list()

In [ ]:
# Ahora veamos las secciones por ciudades:
vigilados_df[vigilados_df['camara_comercio'].isin(ciudades_vigilados)].groupby(['ciuu_seccion_desc', 'camara_comercio']).size().unstack()

camara_comercio,BARRANQUILLA,BOGOTA,BUCARAMANGA,CALI,CARTAGENA,IBAGUE,MEDELLIN PARA ANTIOQUIA,PASTO,TUNJA,VILLAVICENCIO
ciuu_seccion_desc,,,,,,,,,,
ACTIVIDADES DE ORGANIZACIONES Y ENTIDADES EXTRATERRITORIALES,NaN,NaN,1.00,NaN,NaN,NaN,6.00,NaN,NaN,NaN
ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO,122.00,194.00,122.00,160.00,82.00,71.00,127.00,67.00,60.00,102.00
ACTIVIDADES FINANCIERAS Y DE SEGUROS,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ACTIVIDADES INMOBILIARIAS,NaN,NaN,2.00,NaN,NaN,NaN,1.00,NaN,NaN,NaN
"ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS",NaN,NaN,NaN,1.00,10.00,NaN,10.00,NaN,NaN,NaN
ALOJAMIENTO Y SERVICIOS DE COMIDA,NaN,90.00,5.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS,6.00,7.00,2.00,4.00,1.00,NaN,7.00,NaN,1.00,1.00
CONSTRUCCIÓN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN
EDUCACIÓN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
INDUSTRIAS MANUFACTURERAS,1.00,10.00,1.00,2.00,NaN,NaN,NaN,NaN,NaN,1.00
INFORMACIÓN Y COMUNICACIONES,NaN,1.00,NaN,3.00,NaN,NaN,NaN,NaN,NaN,NaN
OTRAS ACTIVIDADES DE SERVICIOS,1.00,NaN,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN
TRANSPORTE Y ALMACENAMIENTO,3.00,5.00,4.00,6.00,2.00,1.00,6.00,NaN,1.00,1.00

In [ ]:
clientes_df['ciuu_seccion_desc'].value_counts().head().to_frame()

                                                    ciuu_seccion_desc
COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓ...              38437
INDUSTRIAS MANUFACTURERAS                                        7304
ACTIVIDADES FINANCIERAS Y DE SEGUROS                             6801
ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RE...               6125
ALOJAMIENTO Y SERVICIOS DE COMIDA                                5659

In [ ]:
clientes_df['camara_comercio'].value_counts().head(20)

CALI                       105806
MEDELLIN PARA ANTIOQUIA     31149
BOGOTA                      26753
BUCARAMANGA                 20685
PEREIRA                     19216
ABURRA SUR                  15961
IBAGUE                      15304
BARRANCABERMEJA             13824
ARMENIA                     11910
BARRANQUILLA                11231
VILLAVICENCIO               11144
CUCUTA                       8745
CARTAGENA                    8717
SANTA MARTA                  8433
CAUCA                        7575
MONTERIA                     7413
HUILA                        6856
VALLEDUPAR                   6806
MANIZALES                    5278
TUMACO                       5170
Name: camara_comercio, dtype: int64

In [ ]:
ciudades_clientes = clientes_df['camara_comercio'].value_counts().head(10).keys().to_list()

In [ ]:
# Ahora veamos las secciones por ciudades:
clientes_df[clientes_df['camara_comercio'].isin(ciudades_clientes)].groupby(['ciuu_seccion_desc', 'camara_comercio']).size().unstack()

camara_comercio,ABURRA SUR,ARMENIA,BARRANCABERMEJA,BARRANQUILLA,BOGOTA,BUCARAMANGA,CALI,IBAGUE,MEDELLIN PARA ANTIOQUIA,PEREIRA
ciuu_seccion_desc,,,,,,,,,,
"ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN",231.00,316.00,142.00,309.00,"1,820.00",418.00,"1,968.00",247.00,797.00,355.00
ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL,244.00,123.00,139.00,696.00,"1,245.00",580.00,"2,366.00",217.00,"1,093.00",178.00
ACTIVIDADES DE LOS HOGARES INDIVIDUALES EN CALIDAD DE EMPLEADORES; ACTIVIDADES NO DIFERENCIADAS DE LOS HOGARES INDIVIDUALES COMO PRODUCTORES DE BIENES Y SERVICIOS PARA USO PROPIO,1.00,NaN,NaN,1.00,NaN,NaN,3.00,NaN,NaN,NaN
ACTIVIDADES DE ORGANIZACIONES Y ENTIDADES EXTRATERRITORIALES,"9,409.00","9,587.00","11,098.00",56.00,4.00,"2,341.00",1.00,"11,492.00","2,560.00","15,415.00"
ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO,193.00,110.00,100.00,433.00,853.00,891.00,"3,299.00",202.00,905.00,197.00
ACTIVIDADES FINANCIERAS Y DE SEGUROS,192.00,148.00,134.00,521.00,"2,409.00","1,598.00","3,307.00",175.00,"1,468.00",213.00
ACTIVIDADES INMOBILIARIAS,107.00,13.00,10.00,138.00,258.00,486.00,"1,721.00",43.00,400.00,27.00
"ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS",174.00,50.00,143.00,297.00,380.00,"1,387.00","4,568.00",140.00,"1,194.00",103.00
ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA,7.00,15.00,10.00,47.00,108.00,56.00,101.00,21.00,60.00,13.00
"AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA",38.00,9.00,61.00,102.00,106.00,277.00,"1,317.00",36.00,204.00,10.00
ALOJAMIENTO Y SERVICIOS DE COMIDA,411.00,164.00,233.00,724.00,"2,686.00",713.00,"10,316.00",221.00,"2,332.00",238.00
COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS,"2,917.00",910.00,938.00,"5,332.00","11,936.00","6,664.00","42,735.00","1,718.00","11,055.00","1,700.00"
CONSTRUCCIÓN,178.00,51.00,262.00,281.00,167.00,729.00,"3,283.00",101.00,605.00,43.00
"DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO AMBIENTAL",12.00,5.00,12.00,51.00,23.00,71.00,706.00,16.00,106.00,2.00
EDUCACIÓN,66.00,19.00,29.00,109.00,332.00,200.00,"1,485.00",46.00,414.00,48.00
EXPLOTACIÓN DE MINAS Y CANTERAS,10.00,NaN,3.00,19.00,28.00,66.00,208.00,6.00,117.00,1.00
INDUSTRIAS MANUFACTURERAS,"1,231.00",181.00,185.00,978.00,"2,337.00","1,999.00","14,209.00",323.00,"3,785.00",262.00
INFORMACIÓN Y COMUNICACIONES,100.00,47.00,58.00,252.00,411.00,263.00,"3,189.00",58.00,553.00,80.00
OTRAS ACTIVIDADES DE SERVICIOS,97.00,52.00,85.00,212.00,276.00,248.00,"4,077.00",74.00,506.00,164.00
"SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO",4.00,10.00,8.00,11.00,34.00,97.00,74.00,9.00,19.00,10.00
TRANSPORTE Y ALMACENAMIENTO,332.00,98.00,172.00,662.00,"1,278.00","1,587.00","6,864.00",157.00,"2,736.00",155.00

### Por Tipo de Servicio

In [ ]:
# Construir un diccionario de nits a tipos de servicio con la base de datos de contratos:
frame = pd.melt(df_Contratos, id_vars=['ID_CONTRATO', 'TIPO_SERVICIO'], value_vars=['NIT_VIGILADO_x', 'NIT_VIGILADO_y', 'NIT_VIGILADO'], var_name='NIT_Column', value_name='NIT_VIGILADO')
frame.drop_duplicates(subset=['TIPO_SERVICIO', 'NIT_VIGILADO'], keep='first', inplace=True, ignore_index=True)
frame['NIT_VIGILADO'] = frame['NIT_VIGILADO'].apply(extender_nit_string)
frame.set_index('NIT_VIGILADO', inplace=True)
nit_tipo_servicio_dict = frame['TIPO_SERVICIO'].to_dict()
frame.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: This dataframe has a column name that matches the 'value_name' column name of the resulting Dataframe. In the future this will raise an error, please set the 'value_name' parameter of DataFrame.melt to a unique name.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ID_CONTRATO,TIPO_SERVICIO,NIT_Column
NIT_VIGILADO,,,
00000811001008,1,Empresa de Vigilancia y Seguridad Privadas sin...,NIT_VIGILADO_x
00000800042276,7,Empresa de Vigilancia y Seguridad Privadas con...,NIT_VIGILADO_x
00000900091901,54,Empresa de Vigilancia y Seguridad Privadas con...,NIT_VIGILADO_x
00000860023264,70,Empresa de Vigilancia y Seguridad Privadas con...,NIT_VIGILADO_x
00000830070625,11904,Empresa de Vigilancia y Seguridad Privadas con...,NIT_VIGILADO_x

In [ ]:
# Asignar el tipo de servicio a cada vigilado
vigilados_df['Tipo_Servicio'] = vigilados_df['nit_propietario'].map(nit_tipo_servicio_dict)
vigilados_df['Tipo_Servicio'].head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

97035      Empresa de Vigilancia y Seguridad Privadas con...
4198382    Empresa de Vigilancia y Seguridad Privadas con...
1991454    Empresa de Vigilancia y Seguridad Privadas con...
4028019    Empresa de Vigilancia y Seguridad Privadas sin...
508550     Empresa de Vigilancia y Seguridad Privadas con...
Name: Tipo_Servicio, dtype: object

In [ ]:
vigilados_df['Tipo_Servicio'].value_counts()

Empresa de Vigilancia y Seguridad Privadas con Armas                                                                                                            1194
Empresa de Vigilancia y Seguridad Privadas sin Armas                                                                                                             617
Cooperativa de Vigilancia y Seguridad Privada                                                                                                                    319
Departamento de Seguridad Persona Jurídica                                                                                                                       108
Inscripción en el Registro de Fabricantes, Importadores, Comercializadores, Arrendadores e Instaladores de Equipos para la Vigilancia y la Seguridad Privada      46
Empresa Blindadora                                                                                                                                                14
Empresa Arrendadora de Vehículos Blindados                                                                                                                         8
Empresa de Transporte de Valores                                                                                                                                   6
Empresa Asesora, Consultora e Investigadora en Vigilancia y Seguridad Privada                                                                                      3
Name: Tipo_Servicio, dtype: int64

In [ ]:
vigilados_df['Tipo_Servicio'].value_counts(normalize=True, dropna = True)

Empresa de Vigilancia y Seguridad Privadas con Armas                                                                                                           0.52
Empresa de Vigilancia y Seguridad Privadas sin Armas                                                                                                           0.27
Cooperativa de Vigilancia y Seguridad Privada                                                                                                                  0.14
Departamento de Seguridad Persona Jurídica                                                                                                                     0.05
Inscripción en el Registro de Fabricantes, Importadores, Comercializadores, Arrendadores e Instaladores de Equipos para la Vigilancia y la Seguridad Privada   0.02
Empresa Blindadora                                                                                                                                             0.01
Empresa Arrendadora de Vehículos Blindados                                                                                                                     0.00
Empresa de Transporte de Valores                                                                                                                               0.00
Empresa Asesora, Consultora e Investigadora en Vigilancia y Seguridad Privada                                                                                  0.00
Name: Tipo_Servicio, dtype: float64

In [ ]:
#Ahora veamos los Tipos de Servicios por ciudades
vigilados_df[vigilados_df['camara_comercio'].isin(ciudades_vigilados)].groupby(['Tipo_Servicio', 'camara_comercio']).size().unstack()

camara_comercio,BARRANQUILLA,BOGOTA,BUCARAMANGA,CALI,CARTAGENA,IBAGUE,MEDELLIN PARA ANTIOQUIA,PASTO,TUNJA,VILLAVICENCIO
Tipo_Servicio,,,,,,,,,,
Cooperativa de Vigilancia y Seguridad Privada,18.00,34.00,23.00,23.00,14.00,11.00,19.00,8.00,6.00,12.00
Departamento de Seguridad Persona Jurídica,1.00,97.00,7.00,1.00,NaN,NaN,1.00,NaN,NaN,1.00
Empresa Arrendadora de Vehículos Blindados,1.00,2.00,1.00,1.00,2.00,NaN,1.00,NaN,NaN,NaN
"Empresa Asesora, Consultora e Investigadora en Vigilancia y Seguridad Privada",1.00,NaN,NaN,1.00,NaN,NaN,1.00,NaN,NaN,NaN
Empresa Blindadora,2.00,8.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN
Empresa de Transporte de Valores,NaN,NaN,2.00,2.00,NaN,NaN,1.00,NaN,NaN,NaN
Empresa de Vigilancia y Seguridad Privadas con Armas,67.00,109.00,64.00,97.00,43.00,44.00,68.00,42.00,40.00,66.00
Empresa de Vigilancia y Seguridad Privadas sin Armas,40.00,56.00,39.00,45.00,31.00,17.00,58.00,17.00,16.00,25.00
"Inscripción en el Registro de Fabricantes, Importadores, Comercializadores, Arrendadores e Instaladores de Equipos para la Vigilancia y la Seguridad Privada",3.00,2.00,4.00,6.00,4.00,NaN,8.00,1.00,NaN,1.00

In [ ]:
vigilados_df.columns

Index(['Unnamed: 0', 'camara_comercio', 'razon_social', 'estado_matricula',
       'ultimo_ano_renovado', 'cod_ciiu_act_econ_pri',
       'codigo_clase_identificacion', 'clase_identificacion',
       'numero_identificacion', 'nit_propietario', 'digito_verificacion',
       'cod_ciiu_act_econ_sec', 'ciuu_division_pri', 'ciuu_division_sec',
       'ciuu_division_pri_desc', 'ciuu_division_sec_desc', 'ciuu_grupo_pri',
       'ciuu_grupo_sec', 'ciuu_grupo_pri_desc', 'ciuu_grupo_sec_desc',
       'ciuu_seccion_desc', 'Tipo_Servicio'],
      dtype='object')

### Por Sector

In [ ]:
df_Contratos['SECTOR_CLIENTE_DESC'].value_counts()

COMERCIAL              38511
RESIDENCIAL            18641
OTRO                   14223
SERVICIOS               9207
VIGILANCIA              6429
INDUSTRIAL              4423
EDUCATIVO               1909
GOBIERNO                1818
TRANSPORTES             1443
FINANCIERO              1363
MINAS Y ENERGIA          536
AGRICOLA Y GANADERO      361
Name: SECTOR_CLIENTE_DESC, dtype: int64

In [ ]:
# Construir un diccionario de nits a sectores con la base de datos de contratos:
frame = df_Contratos[['NUMERO_DOCUMENTO_CLIENTE', 'SECTOR_CLIENTE_DESC']]
frame.drop_duplicates(keep='first', inplace=True, ignore_index=True)
frame.dropna(inplace = True)
frame['NUMERO_DOCUMENTO_CLIENTE'] = frame['NUMERO_DOCUMENTO_CLIENTE'].apply(extender_nit_string)
frame.set_index('NUMERO_DOCUMENTO_CLIENTE', inplace=True)
nit_sector_dict = frame['SECTOR_CLIENTE_DESC'].to_dict()
frame.head()

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

                         SECTOR_CLIENTE_DESC
NUMERO_DOCUMENTO_CLIENTE
00000890920369                     COMERCIAL
00000800106884                     COMERCIAL
00000800169068                     COMERCIAL
00000900196221                     COMERCIAL
00000900030978                     COMERCIAL

In [ ]:
# Tabla de equivalencia de Sector a Seccion de Códigos CIUU del DANE:

PATH = '/content/drive/MyDrive/Observatorio SPVS/BD RENOVA - Contratos Todos los Clientes/Tabla correlativa CIIU 4 A.C. (2020) - CIIU 4 A.C. (2021).xlsx'
CIIU_sector_df = pd.read_excel(PATH,  sheet_name='Seccion CIIU a Sector') # encoding = 'utf-8', dtype='str', sep=',' ) #
CIIU_sector_df.shape

(21, 4)

In [ ]:
CIIU_sector_df.head()

,Código,Descripción,Seccion,Seccion_Desc
0,5.00,AGRICOLA Y GANADERO,SECCIÓN A,"AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y P..."
1,8.00,MINAS Y ENERGIA,SECCIÓN B,EXPLOTACIÓN DE MINAS Y CANTERAS
2,4.00,INDUSTRIAL,SECCIÓN C,INDUSTRIAS MANUFACTURERAS
3,8.00,MINAS Y ENERGIA,SECCIÓN D,"SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ..."
4,12.00,OTRO,SECCIÓN E,DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO...

In [ ]:

# Crear un diccionario de seccion a sector:
CIIU_sector_df.set_index('Seccion_Desc', inplace = True)
ciuu_seccion_sector_dict = CIIU_sector_df['Descripción'].to_dict()

In [ ]:
clientes_df.columns

Index(['Unnamed: 0', 'camara_comercio', 'razon_social', 'estado_matricula',
       'ultimo_ano_renovado', 'cod_ciiu_act_econ_pri',
       'codigo_clase_identificacion', 'clase_identificacion',
       'numero_identificacion', 'nit_propietario', 'digito_verificacion',
       'cod_ciiu_act_econ_sec', 'ciuu_division_pri', 'ciuu_division_sec',
       'ciuu_division_pri_desc', 'ciuu_division_sec_desc', 'ciuu_grupo_pri',
       'ciuu_grupo_sec', 'ciuu_grupo_pri_desc', 'ciuu_grupo_sec_desc',
       'ciuu_seccion_desc'],
      dtype='object')

In [ ]:
# Asignar el sector a cada cliente
clientes_df['Sector'] = clientes_df['ciuu_seccion_desc'].map(ciuu_seccion_sector_dict)
clientes_df.loc[clientes_df['Sector'].isna(), 'Sector'] = clientes_df['nit_propietario'].map(nit_sector_dict)
clientes_df['Sector'].head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

0    SERVICIOS
1    COMERCIAL
2     GOBIERNO
3     GOBIERNO
4     GOBIERNO
Name: Sector, dtype: object

In [ ]:
clientes_df['Sector'].value_counts().to_frame()

                     Sector
COMERCIAL             38437
FINANCIERO            12926
SERVICIOS             11900
INDUSTRIAL             8495
RESIDENCIAL            6644
TRANSPORTES            4943
EDUCATIVO               908
AGRICOLA Y GANADERO     606
GOBIERNO                600
MINAS Y ENERGIA         311
OTRO                    208

In [ ]:
clientes_df['Sector'].value_counts(normalize=True, dropna = True).to_frame()

                     Sector
COMERCIAL              0.45
FINANCIERO             0.15
SERVICIOS              0.14
INDUSTRIAL             0.10
RESIDENCIAL            0.08
TRANSPORTES            0.06
EDUCATIVO              0.01
AGRICOLA Y GANADERO    0.01
GOBIERNO               0.01
MINAS Y ENERGIA        0.00
OTRO                   0.00

In [ ]:
# Ahora veamos los sectores por ciudades

clientes_df[clientes_df['camara_comercio'].isin(ciudades_clientes)].groupby(['Sector', 'camara_comercio']).size().unstack()

camara_comercio,ABURRA SUR,ARMENIA,BARRANCABERMEJA,BARRANQUILLA,BOGOTA,BUCARAMANGA,CALI,IBAGUE,MEDELLIN PARA ANTIOQUIA,PEREIRA
Sector,,,,,,,,,,
AGRICOLA Y GANADERO,38,9,61,102,106,277,1317,36,204,10
COMERCIAL,2921,911,938,5332,11960,6664,42735,1718,11098,1702
EDUCATIVO,66,19,29,109,332,200,1485,46,414,48
FINANCIERO,423,464,276,830,4232,2016,5276,422,2265,568
GOBIERNO,9416,9602,11108,103,113,2397,102,11513,2620,15428
INDUSTRIAL,1409,232,447,1259,2506,2728,17492,424,4397,305
MINAS Y ENERGIA,14,10,11,30,62,163,282,15,136,11
OTRO,13,5,12,51,29,71,706,16,127,2
RESIDENCIAL,519,178,244,863,2945,1213,12048,266,2737,265
SERVICIOS,808,382,526,1890,3169,3369,17499,691,4259,722
TRANSPORTES,332,98,172,662,1278,1587,6864,157,2737,155

#### guardar archivos

In [ ]:
#vigilados_df.to_csv('vigilados_registrados_RUES.csv')
#clientes_df.to_csv('clientes_registrados_RUES.csv')

In [ ]:
vigilados_df = pd.read_csv('vigilados_registrados_RUES.csv')
clientes_df = pd.read_csv('clientes_registrados_RUES.csv')

# Step 4: Completar la información de los Contratos

In [ ]:
vigilados_df_sinduplicados = vigilados_df.drop_duplicates(subset=['nit_propietario'], keep='first', ignore_index=True)
clientes_df_sinduplicados = clientes_df.drop_duplicates(subset=['nit_propietario'], keep='first', ignore_index=True)

In [ ]:
# Diccionario de clientes a CIIU
clientes_frame = clientes_df_sinduplicados[['nit_propietario',
       'cod_ciiu_act_econ_pri','ciuu_division_pri', 'ciuu_division_pri_desc', 'ciuu_grupo_pri',
       'ciuu_grupo_pri_desc', 'ciuu_seccion_desc', 'Sector']]
clientes_frame.head()

,nit_propietario,cod_ciiu_act_econ_pri,ciuu_division_pri,ciuu_division_pri_desc,ciuu_grupo_pri,ciuu_grupo_pri_desc,ciuu_seccion_desc,Sector
0,00000000000000,5229,52,Almacenamiento y actividades complementarias a...,522,"Actividades de las estaciones, vías y servicio...",TRANSPORTE Y ALMACENAMIENTO,TRANSPORTES
1,00000860034313,6412,64,"Actividades de servicios financieros, excepto ...",641,Intermediación monetaria,ACTIVIDADES FINANCIERAS Y DE SEGUROS,FINANCIERO
2,00000860002153,5210,52,Almacenamiento y actividades complementarias a...,521,Almacenamiento y depósito,TRANSPORTE Y ALMACENAMIENTO,TRANSPORTES
3,00000800233052,4923,49,Transporte terrestre; transporte por tuberías,492,Transporte terrestre público automotor,TRANSPORTE Y ALMACENAMIENTO,TRANSPORTES
4,00000800001520,9200,92,Actividades de juegos de azar y apuestas,920,Actividades de juegos de azar y apuestas,"ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y R...",FINANCIERO

In [ ]:
df_Contratos2 = df_Contratos.copy()

In [ ]:
df_Contratos2['NUMERO_DOCUMENTO_CLIENTE'] = df_Contratos2['NUMERO_DOCUMENTO_CLIENTE'].apply(extender_nit_string)

In [ ]:
df_Contratos2 = pd.merge(df_Contratos2, clientes_frame, how='left', left_on='NUMERO_DOCUMENTO_CLIENTE', right_on='nit_propietario')
df_Contratos2.head()

,Unnamed: 0,ID_CONTRATO,FECHA_INICIO_CONTRATO,FECHA_FIN_CONTRATO,MONTO_CONTRATO,CANTIDAD_PUESTOS_CONTRATO,NIT_VIGILADO_x,DESCRIPCION_VALOR_AGREGADO,ID_ESTADO_CONTRATO,FECHA_CONTRATO_ESTADO,MAXDATE,MINDATE,ID_CLIENTE,TIPO_CONTRATO,ACTIVO_x,NUMERO_DOCUMENTO_CLIENTE,DIGITO_VERIFICACION,RAZON_SOCIAL_CLIENTE,PRIMER_NOMBRE_CLIENTE,SEGUNDO_NOMBRE_CLIENTE,PRIMER_APELLIDO_CLIENTE,SEGUNDO_APELIDO_CLIENTE,SECTOR_CLIENTE,CIIU_CLIENTE,DIRECCION_CLIENTE,TELEFONO_FIJO_CLIENTE,TELEFONO_MOVIL_CLIENTE,CORREO_ELECTRONICO_CLIENTE,CORREO_ELECTRONICO_ALTERNATIVO_CLIENTE,ID_CIUDAD,ID_DEPARTAMENTO,ID_DEPARTAMENTO1,ID_TIPO_DOCUMENTO_IDENTIFICACION,NUMERO_DOCUMENTO_REPRESENTANTE_LEGAL_CLIENTE,ID_TIPO_CLIENTE,TIPO_VIA,NOMBRE_NUM_VIA,PREFIJO_UNO,PREFIJO_UNO_UNO,NUMERO_VIA_GENERADORA,PREFIJO_DOS,PREFIJO_DOS_DOS,NUMERO_PLACA,COMPLEMENTARIO_LISTA,COMPLEMENTARIO_TEXTO,ID_TIPO_DOCUMENTO_IDENTIFICACION_REPRESENTANTE_LEGAL_CLIENTE,NIT_VIGILADO_y,CONSORCIO,ID_DIRECCION,ACTIVO_y,NIT_VIGILADO,ID_TIPO_SERVICIO,ID_TIPO_SOCIEDAD,RAZON_SOCIAL_VIGILADO,CIIU_VIGILADO,TIPO_SERVICIO,SECTOR_CLIENTE_DESC,nit_propietario,cod_ciiu_act_econ_pri,ciuu_division_pri,ciuu_division_pri_desc,ciuu_grupo_pri,ciuu_grupo_pri_desc,ciuu_seccion_desc,Sector
0,0,1,2011-08-02 00:00:00.000,2012-08-01 00:00:00.000,0.0,2.0,811001008,NaN,NaN,NaN,NaN,NaN,306,NaN,1,00000890920369,9,INDUSTRIAS EL TORO LTDA,RAFAEL,NaN,SANCHEZ,FRAN,1.0,1810,null null null null null null null null,2313506,0342313506,televigia@televigia.com,andicasta888@hotmail.com,5001.0,5.0,5.0,4,6783521,1,CARRERA,56,C,NaN,50.0,NaN,NaN,30.0,LOCAL,301,1.0,811001008,0.0,160029,1,811001008,2,2,TELEVIGIA,8020,Empresa de Vigilancia y Seguridad Privadas sin...,COMERCIAL,00000890920369,1410,14,Confección de prendas de vestir,141,"Confección de prendas de vestir, excepto prend...",INDUSTRIAS MANUFACTURERAS,INDUSTRIAL
1,1,3,2011-08-02 00:00:00.000,2012-08-01 00:00:00.000,37659.0,1.0,811001008,NaN,NaN,NaN,NaN,NaN,306,NaN,1,00000890920369,9,INDUSTRIAS EL TORO LTDA,RAFAEL,NaN,SANCHEZ,FRAN,1.0,1810,null null null null null null null null,2313506,0342313506,televigia@televigia.com,andicasta888@hotmail.com,5001.0,5.0,5.0,4,6783521,1,CARRERA,56,C,NaN,50.0,NaN,NaN,30.0,LOCAL,301,1.0,811001008,0.0,160029,1,811001008,2,2,TELEVIGIA,8020,Empresa de Vigilancia y Seguridad Privadas sin...,COMERCIAL,00000890920369,1410,14,Confección de prendas de vestir,141,"Confección de prendas de vestir, excepto prend...",INDUSTRIAS MANUFACTURERAS,INDUSTRIAL
2,2,4,2011-08-02 00:00:00.000,2012-08-01 00:00:00.000,177520.0,9.0,811001008,NaN,NaN,NaN,NaN,NaN,306,NaN,1,00000890920369,9,INDUSTRIAS EL TORO LTDA,RAFAEL,NaN,SANCHEZ,FRAN,1.0,1810,null null null null null null null null,2313506,0342313506,televigia@televigia.com,andicasta888@hotmail.com,5001.0,5.0,5.0,4,6783521,1,CARRERA,56,C,NaN,50.0,NaN,NaN,30.0,LOCAL,301,1.0,811001008,0.0,160029,1,811001008,2,2,TELEVIGIA,8020,Empresa de Vigilancia y Seguridad Privadas sin...,COMERCIAL,00000890920369,1410,14,Confección de prendas de vestir,141,"Confección de prendas de vestir, excepto prend...",INDUSTRIAS MANUFACTURERAS,INDUSTRIAL
3,3,6,2011-08-02 00:00:00.000,2012-08-01 00:00:00.000,37659.0,1.0,811001008,NaN,NaN,NaN,NaN,NaN,306,NaN,1,00000890920369,9,INDUSTRIAS EL TORO LTDA,RAFAEL,NaN,SANCHEZ,FRAN,1.0,1810,null null null null null null null null,2313506,0342313506,televigia@televigia.com,andicasta888@hotmail.com,5001.0,5.0,5.0,4,6783521,1,CARRERA,56,C,NaN,50.0,NaN,NaN,30.0,LOCAL,301,1.0,811001008,0.0,160029,1,811001008,2,2,TELEVIGIA,8020,Empresa de Vigilancia y Seguridad Privadas sin...,COMERCIAL,00000890920369,1410,14,Confección de prendas de vestir,141,"Confección de prendas de vestir, excepto prend...",INDUSTRIAS MANUFACTURERAS,INDUSTRIAL
4,4,8,2011-08-02 00:00:00.000,2012-08-01 00:00:00.000,37659.0,1.0,811001008,NaN,NaN,NaN,NaN,NaN,306,NaN,1,00000890920369,9,INDUSTRIAS EL TORO LTDA,RAFAEL,NaN,SANCHEZ,FRAN,1.0,1810,null null null null null null null null,2313506,0342313506,televigia@televigia.com,andicasta888@hotmail.com,5001.0,5.0,5.0,4,6783521,1,CARRERA,56,C,NaN,50.0,NaN,NaN,30.0,LOCAL,301,1.0,811001008,0.0,160029,1,811001008,2,2,TELEVIGIA,8020,Empresa de Vigilancia y Seguridad Privadas sin...,COMERCIAL,00000890920369,1410,14,Confección de prendas de vestir,141,"Confección de prendas de vestir, excepto prend...",INDUSTRIAS MANUFACTURERAS,INDUSTRIAL

In [ ]:
df_Contratos2.to_csv('contratos_RENOVA_todos_los_clientes_con_Datos_de_RUES.csv')

# Step 5: Estadísticas de actividades económicas de los Contratos

In [ ]:
df_Contratos2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 177614 entries, 0 to 177613
Data columns (total 65 columns):
 #   Column                                                        Non-Null Count   Dtype
---  ------                                                        --------------   -----
 0   Unnamed: 0                                                    177614 non-null  object
 1   ID_CONTRATO                                                   177614 non-null  object
 2   FECHA_INICIO_CONTRATO                                         177614 non-null  object
 3   FECHA_FIN_CONTRATO                                            177614 non-null  object
 4   MONTO_CONTRATO                                                177614 non-null  object
 5   CANTIDAD_PUESTOS_CONTRATO                                     62366 non-null   object
 6   NIT_VIGILADO_x                                                177614 non-null  object
 7   DESCRIPCION_VALOR_AGREGADO                                    9496 non-null    object
 8   ID_ESTADO_CONTRATO                                            39171 non-null   object
 9   FECHA_CONTRATO_ESTADO                                         39169 non-null   object
 10  MAXDATE                                                       20365 non-null   object
 11  MINDATE                                                       14657 non-null   object
 12  ID_CLIENTE                                                    177614 non-null  object
 13  TIPO_CONTRATO                                                 98182 non-null   object
 14  ACTIVO_x                                                      177614 non-null  object
 15  NUMERO_DOCUMENTO_CLIENTE                                      177614 non-null  object
 16  DIGITO_VERIFICACION                                           126788 non-null  object
 17  RAZON_SOCIAL_CLIENTE                                          126262 non-null  object
 18  PRIMER_NOMBRE_CLIENTE                                         99440 non-null   object
 19  SEGUNDO_NOMBRE_CLIENTE                                        56961 non-null   object
 20  PRIMER_APELLIDO_CLIENTE                                       99411 non-null   object
 21  SEGUNDO_APELIDO_CLIENTE                                       67510 non-null   object
 22  SECTOR_CLIENTE                                                98864 non-null   object
 23  CIIU_CLIENTE                                                  16865 non-null   object
 24  DIRECCION_CLIENTE                                             176446 non-null  object
 25  TELEFONO_FIJO_CLIENTE                                         177614 non-null  object
 26  TELEFONO_MOVIL_CLIENTE                                        51225 non-null   object
 27  CORREO_ELECTRONICO_CLIENTE                                    177614 non-null  object
 28  CORREO_ELECTRONICO_ALTERNATIVO_CLIENTE                        10110 non-null   object
 29  ID_CIUDAD                                                     170939 non-null  object
 30  ID_DEPARTAMENTO                                               170939 non-null  object
 31  ID_DEPARTAMENTO1                                              169923 non-null  object
 32  ID_TIPO_DOCUMENTO_IDENTIFICACION                              177614 non-null  object
 33  NUMERO_DOCUMENTO_REPRESENTANTE_LEGAL_CLIENTE                  92231 non-null   object
 34  ID_TIPO_CLIENTE                                               177614 non-null  object
 35  TIPO_VIA                                                      169923 non-null  object
 36  NOMBRE_NUM_VIA                                                169923 non-null  object
 37  PREFIJO_UNO                                                   46728 non-null   object
 38  PREFIJO_UNO_UNO                                               7032 non-null    object
 39  NUMERO_VIA_GENERADORA                                         169923 non-null  object
 40  PREFIJO_DOS                                                   44692 non-null   object
 41  PREFIJO_DOS_DOS                                               5794 non-null    object
 42  NUMERO_PLACA                                                  169923 non-null  object
 43  COMPLEMENTARIO_LISTA                                          53334 non-null   object
 44  COMPLEMENTARIO_TEXTO                                          51816 non-null   object
 45  ID_TIPO_DOCUMENTO_IDENTIFICACION_REPRESENTANTE_LEGAL_CLIENTE  91528 non-null   object
 46  NIT_VIGILADO_y                                                177614 non-null  object
 47  CONSORCIO                                                     175633 non-null  object
 48  ID_DIRECCION                                                  177614 non-null  object
 49  ACTIVO_y                                                      177614 non-null  object
 50  NIT_VIGILADO                                                  177614 non-null  object
 51  ID_TIPO_SERVICIO                                              177614 non-null  object
 52  ID_TIPO_SOCIEDAD                                              177614 non-null  object
 53  RAZON_SOCIAL_VIGILADO                                         177614 non-null  object
 54  CIIU_VIGILADO                                                 177614 non-null  object
 55  TIPO_SERVICIO                                                 177614 non-null  object
 56  SECTOR_CLIENTE_DESC                                           98864 non-null   object
 57  nit_propietario                                               58331 non-null   object
 58  cod_ciiu_act_econ_pri                                         58331 non-null   object
 59  ciuu_division_pri                                             58331 non-null   object
 60  ciuu_division_pri_desc                                        58326 non-null   object
 61  ciuu_grupo_pri                                                58331 non-null   object
 62  ciuu_grupo_pri_desc                                           57273 non-null   object
 63  ciuu_seccion_desc                                             58326 non-null   object
 64  Sector                                                        58326 non-null   object
dtypes: object(65)
memory usage: 89.4+ MB

In [ ]:
df_Contratos2['SECTOR_CLIENTE_DESC'].value_counts().to_frame()

                     SECTOR_CLIENTE_DESC
COMERCIAL                          38511
RESIDENCIAL                        18641
OTRO                               14223
SERVICIOS                           9207
VIGILANCIA                          6429
INDUSTRIAL                          4423
EDUCATIVO                           1909
GOBIERNO                            1818
TRANSPORTES                         1443
FINANCIERO                          1363
MINAS Y ENERGIA                      536
AGRICOLA Y GANADERO                  361

In [ ]:
df_Contratos2['SECTOR_CLIENTE_DESC'].value_counts(normalize=True, dropna = True).to_frame()

                     SECTOR_CLIENTE_DESC
COMERCIAL                           0.39
RESIDENCIAL                         0.19
OTRO                                0.14
SERVICIOS                           0.09
VIGILANCIA                          0.07
INDUSTRIAL                          0.04
EDUCATIVO                           0.02
GOBIERNO                            0.02
TRANSPORTES                         0.01
FINANCIERO                          0.01
MINAS Y ENERGIA                     0.01
AGRICOLA Y GANADERO                 0.00

In [ ]:
df_Contratos2['ciuu_seccion_desc'].value_counts().to_frame()

                                                    ciuu_seccion_desc
COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓ...              20428
ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE A...               9402
INDUSTRIAS MANUFACTURERAS                                        7053
TRANSPORTE Y ALMACENAMIENTO                                      3199
ACTIVIDADES FINANCIERAS Y DE SEGUROS                             2787
CONSTRUCCIÓN                                                     2668
ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE...               2605
ALOJAMIENTO Y SERVICIOS DE COMIDA                                2546
ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS                1572
ACTIVIDADES INMOBILIARIAS                                        1076
INFORMACIÓN Y COMUNICACIONES                                      938
OTRAS ACTIVIDADES DE SERVICIOS                                    772
EDUCACIÓN                                                         771
ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RE...                769
AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA                470
EXPLOTACIÓN DE MINAS Y CANTERAS                                   454
DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO ...                270
SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE A...                264
ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEG...                153
ACTIVIDADES DE ORGANIZACIONES Y ENTIDADES EXTRA...                129

In [ ]:
df_Contratos2['ciuu_seccion_desc'].value_counts(normalize=True, dropna = True).to_frame()

                                                    ciuu_seccion_desc
COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓ...               0.35
ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE A...               0.16
INDUSTRIAS MANUFACTURERAS                                        0.12
TRANSPORTE Y ALMACENAMIENTO                                      0.05
ACTIVIDADES FINANCIERAS Y DE SEGUROS                             0.05
CONSTRUCCIÓN                                                     0.05
ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE...               0.04
ALOJAMIENTO Y SERVICIOS DE COMIDA                                0.04
ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS                0.03
ACTIVIDADES INMOBILIARIAS                                        0.02
INFORMACIÓN Y COMUNICACIONES                                     0.02
OTRAS ACTIVIDADES DE SERVICIOS                                   0.01
EDUCACIÓN                                                        0.01
ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RE...               0.01
AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA               0.01
EXPLOTACIÓN DE MINAS Y CANTERAS                                  0.01
DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO ...               0.00
SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE A...               0.00
ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEG...               0.00
ACTIVIDADES DE ORGANIZACIONES Y ENTIDADES EXTRA...               0.00

In [ ]:
df_Contratos2['ID_CIUDAD'].value_counts().head()

11001.0    48037
5001.0     36026
76001.0    15266
8001.0      8355
13001.0     4373
Name: ID_CIUDAD, dtype: int64

In [ ]:
df_Contratos2['ID_DEPARTAMENTO'].value_counts().head()

5.0     49715
11.0    48037
76.0    17959
8.0      8866
25.0     6290
Name: ID_DEPARTAMENTO, dtype: int64

In [ ]:
df_Contratos2['ID_DEPARTAMENTO1'].value_counts().head()

5.0     49714
11.0    47956
76.0    17954
8.0      8860
25.0     6273
Name: ID_DEPARTAMENTO1, dtype: int64

In [ ]:
df_Contratos2.groupby(['SECTOR_CLIENTE_DESC', 'ID_CIUDAD']).size().unstack()

ID_CIUDAD,11001.0,13001.0,17001.0,17380.0,19001.0,20001.0,20011.0,20710.0,23001.0,25035.0,25126.0,25175.0,25214.0,25260.0,25286.0,25430.0,25473.0,25486.0,25799.0,25875.0,25899.0,41001.0,47001.0,50001.0,5001.0,50226.0,5045.0,5088.0,5148.0,5266.0,5308.0,5318.0,54001.0,5615.0,5631.0,5679.0,5789.0,5887.0,63001.0,66001.0,66400.0,68001.0,68081.0,68307.0,70001.0,73001.0,73408.0,73547.0,73563.0,76001.0,76109.0,76520.0,8001.0,85010.0,85230.0,13006.0,13244.0,13430.0,13683.0,13688.0,13836.0,15001.0,15104.0,15176.0,15238.0,15299.0,15407.0,15469.0,15491.0,15516.0,15646.0,15759.0,15806.0,17174.0,17541.0,17614.0,17873.0,17877.0,18001.0,18753.0,19130.0,19142.0,19212.0,19256.0,19300.0,19548.0,19573.0,19698.0,19780.0,19807.0,20013.0,20060.0,20443.0,23162.0,23189.0,23417.0,23466.0,23555.0,23660.0,23807.0,25001.0,25019.0,25099.0,25148.0,25151.0,25269.0,25281.0,25290.0,25293.0,25295.0,25297.0,25307.0,25320.0,25322.0,25377.0,25386.0,25407.0,25740.0,25743.0,25754.0,25758.0,25785.0,25817.0,25843.0,27001.0,27361.0,41298.0,41349.0,41357.0,41524.0,41551.0,41668.0,44001.0,44430.0,44650.0,47189.0,47288.0,47707.0,50006.0,5002.0,50150.0,5030.0,50313.0,5034.0,5042.0,5044.0,50568.0,50606.0,50689.0,5079.0,5101.0,5113.0,5129.0,5147.0,5154.0,5172.0,5197.0,52001.0,5209.0,5212.0,52356.0,5237.0,52399.0,5264.0,52835.0,52838.0,5310.0,5313.0,5360.0,5364.0,5376.0,5380.0,5390.0,5400.0,5440.0,54498.0,54518.0,54874.0,5541.0,5607.0,5642.0,5656.0,5660.0,5664.0,5667.0,5686.0,5697.0,5756.0,5761.0,5837.0,5856.0,5893.0,5895.0,63130.0,63401.0,63594.0,66088.0,66170.0,66383.0,66440.0,66594.0,66682.0,68077.0,68092.0,68276.0,68406.0,68418.0,68432.0,68522.0,68547.0,68655.0,68679.0,68755.0,68773.0,68861.0,70708.0,73124.0,73168.0,73268.0,73275.0,73319.0,73349.0,73443.0,73449.0,73504.0,73671.0,73861.0,76020.0,76036.0,76041.0,76111.0,76113.0,76130.0,76147.0,76248.0,76318.0,76364.0,76403.0,76622.0,76736.0,76823.0,76834.0,76892.0,76895.0,8078.0,81001.0,8296.0,8433.0,85001.0,85250.0,85410.0,8560.0,8573.0,86568.0,86749.0,8685.0,8758.0,88001.0,91001.0,95001.0,17513.0,20621.0,25513.0,25572.0,25718.0,25841.0,63212.0,86001.0,8638.0,5021.0,5604.0,15753.0,18756.0,19473.0,19517.0,19532.0,19845.0,20045.0,20400.0,23182.0,23672.0,25053.0,25200.0,25312.0,25335.0,25402.0,25488.0,25612.0,44035.0,44279.0,50287.0,50318.0,50680.0,54313.0,54405.0,5579.0,5736.0,70215.0,70823.0,85440.0,8849.0,94001.0,97001.0,99001.0,15542.0,17442.0,20770.0,25491.0,44078.0,47058.0,47245.0,50110.0,50124.0,50573.0,68549.0,68669.0,68705.0,70523.0,70771.0,73770.0,76233.0,76275.0,76670.0,76869.0,15667.0,23580.0,25317.0,25793.0,41016.0,73411.0,86885.0,13052.0,15322.0,15693.0,17042.0,17653.0,19622.0,20175.0,20228.0,20238.0,25154.0,25178.0,25658.0,25736.0,25769.0,25815.0,41885.0,44560.0,47980.0,5038.0,5086.0,52473.0,52480.0,5284.0,5321.0,5353.0,5847.0,5890.0,63190.0,63302.0,63470.0,66045.0,66075.0,68176.0,70110.0,76563.0,76616.0,76828.0,76863.0,8372.0,85430.0,86573.0,15204.0,15599.0,15673.0,25040.0,25483.0,5809.0,70221.0,76606.0,13657.0,13744.0,15514.0,15764.0,19450.0,20787.0,25183.0,41006.0,41791.0,44378.0,47555.0,47798.0,54003.0,54810.0,68615.0,73148.0,73200.0,73217.0,76400.0,86760.0,13838.0,44874.0,15572.0,17013.0,5250.0,5368.0,5858.0,81736.0
SECTOR_CLIENTE_DESC,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
AGRICOLA Y GANADERO,97.00,2.00,3.00,1.00,11.00,2.00,2.00,2.00,3.00,1.00,10.00,1.00,9.00,1.00,1.00,1.00,5.00,2.00,5.00,2.00,3.00,3.00,8.00,15.00,22.00,2.00,2.00,1.00,2.00,2.00,1.00,1.00,5.00,1.00,6.00,1.00,2.00,1.00,1.00,2.00,1.00,20.00,5.00,2.00,2.00,1.00,2.00,1.00,1.00,21.00,1.00,9.00,6.00,3.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COMERCIAL,"8,828.00","1,594.00",297.00,4.00,628.00,268.00,16.00,NaN,355.00,NaN,16.00,78.00,360.00,2.00,89.00,12.00,38.00,1.00,7.00,NaN,6.00,57.00,308.00,317.00,"7,937.00",1.00,41.00,207.00,5.00,458.00,21.00,34.00,433.00,220.00,216.00,NaN,NaN,2.00,161.00,"1,185.00",9.00,"1,252.00",153.00,105.00,158.00,"1,623.00",2.00,NaN,1.00,"3,795.00",37.00,48.00,"1,455.00",2.00,NaN,2.00,3.00,2.00,1.00,2.00,26.00,135.00,2.00,4.00,24.00,1.00,5.00,11.00,1.00,1.00,2.00,28.00,1.00,9.00,4.00,1.00,9.00,1.00,10.00,2.00,2.00,2.00,1.00,1.00,4.00,1.00,5.00,16.00,3.00,1.00,1.00,2.00,2.00,4.00,1.00,3.00,2.00,11.00,1.00,4.00,2.00,1.00,2.00,1.00,1.00,13.00,2.00,13.00,4.00,3.00,1.00,52.00,1.00,2.00,18.00,1.00,1.00,2.00,6.00,25.00,7.00,3.00,120.00,1.00,7.00,2.00,1.00,1.00,1.00,1.00,7.00,2.00,14.00,1.00,1.00,10.00,3.00,1.00,2.00,2.00,3.00,4.00,2.00,10.00,6.00,1.00,2.00,4.00,2.00,6.00,3.00,1.00,107.00,4.00,15.00,4.00,1.00,494.00,2.00,34.00,95.00,7.00,1.00,2.00,25.00,2.00,1.00,3.00,548.00,2.00,30.00,103.00,6.00,8.00,15.00,8.00,1.00,6.00,1.00,29.00,6.00,4.00,1.00,1.00,1.00,12.00,5.00,1.00,6.00,9.00,1.00,1.00,1.00,1.00,6.00,1.00,3.00,136.00,25.00,1.00,2.00,10.00,4.00,1.00,84.00,5.00,2.00,2.00,1.00,40.00,4.00,3.00,3.00,1.00,1.00,2.00,21.00,2.00,31.00,1.00,22.00,6.00,18.00,2.00,2.00,8.00,1.00,4.00,2.00,1.00,23.00,4.00,13.00,170.00,3.00,2.00,26.00,1.00,3.00,1.00,1.00,19.00,109.00,8.00,1.00,3.00,2.00,9.00,34.00,1.00,2.00,1.00,6.00,1.00,1.00,1.00,31.00,18.00,5.00,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EDUCATIVO,507.00,50.00,11.00,NaN,83.00,30.00,NaN,NaN,36.00,NaN,NaN,13.00,5.00,NaN,1.00,6.00,3.00,NaN,NaN,NaN,NaN,6.00,35.00,45.00,282.00,NaN,1.00,10.00,10.00,11.00,1.00,9.00,26.00,12.00,14.00,NaN,NaN,NaN,5.00,99.00,NaN,80.00,5.00,NaN,5.00,44.00,1.00,NaN,NaN,94.00,3.00,5.00,73.00,NaN,NaN,NaN,NaN,3.00,NaN,NaN,1.00,17.00,NaN,NaN,9.00,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,7.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,6.00,NaN,1.00,NaN,NaN,4.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00,NaN,3.00,7.00,NaN,NaN,5.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.00,NaN,NaN,NaN,3.00,NaN,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,9.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,13.00,NaN,NaN,NaN,8.00,NaN,NaN,NaN,3.00,2.00,1.00,NaN,2.00,1.00,2.00,1.00,1.00,1.00,1.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FINANCIERO,657.00,7.00,4.00,NaN,10.00,3.00,2.00,NaN,10.00,NaN,NaN,5.00,2.00,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,3.00,5.00,298.00,NaN,NaN,3.00,NaN,NaN,NaN,NaN,3.00,3.00,1.00,NaN,2.00,NaN,3.00,44.00,NaN,70.00,6.00,NaN,7.00,11.00,NaN,NaN,NaN,97.00,9.00,1.00,22.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,1.00,NaN,1.00,3.00,NaN,NaN,NaN,1.00,NaN,NaN,NaN,10.00,NaN,2.00,1.00,NaN,NaN,NaN,3.00,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,3.00,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GOBIERNO,727.00,32.00,19.00,NaN,50.00,15.00,NaN,NaN,20.00,NaN,2.00,NaN,NaN,NaN,5.00,2.00,NaN,NaN,1.00,2.00,3.00,11.00,45.00,82.00,136.00,NaN,2.00,4.00,1.00,5.00,1.00,7.00,16.00,2.00,2.00,NaN,1.00,1.00,1.00,25.00,NaN,17.00,6.00,1.00,20.00,13.00,1.00,NaN,NaN,25.00,1.00,1.00,17.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.00,NaN,3.00,4.00,NaN,3.00,NaN,NaN,6.00,NaN,2.00,4.00,NaN,NaN,NaN,NaN,NaN,4.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,2.00,4.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,4.00,2.00,1.00,NaN,2.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.00,NaN,2.00,NaN,1.00,NaN,5.00,NaN,11.00,NaN,5.00,NaN,NaN,NaN,9.00,5.00,6.00,2.00,NaN,NaN,NaN,NaN,NaN,1.00,NaN,38.00,NaN,NaN,1.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,5.00,NaN,2.00,5.00,NaN,NaN,NaN,2.00,NaN,1.00,NaN,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,2.00,NaN,7.00,3.00,NaN,NaN,NaN,2.00,1.00,2.00,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,1.00,1.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,4.00,NaN,NaN,17.00,NaN,1.00,27.00,11.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,10.00,2.00,5.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,4.00,NaN,NaN,NaN,1.00,2.00,1.00,2.00,2.00,2.00,3.00,2.00,1.00,1.00,1.00,6.00,1.00,1.00,5.00,4.00,1.00,1.00,1.00,10.00,5.00,5.00,2.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,3.00,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
INDUSTRIAL,"1,242.00",209.00,51.00,NaN,14.00,6.00,1.00,NaN,24.00,NaN,12.00,19.00,14.00,3.00,32.00,12.00,16.00,NaN,9.00,NaN,2.00,18.00,41.00,42.00,788.00,NaN,1.00,14.00,NaN,44.00,8.00,7.00,46.00,37.00,121.00,NaN,NaN,NaN,4.00,67.00,8.00,130.00,18.00,39.00,13.00,29.00,NaN,NaN,NaN,315.00,8.00,35.00,214.00,3.00,NaN,NaN,1.00,NaN,NaN,NaN,2.00,23.00,NaN,NaN,2.00,NaN,NaN,NaN,1.00,NaN,1.00,7.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.00,NaN,NaN,NaN,NaN,11.00,8.00,NaN,NaN,NaN,NaN,NaN,8.00,NaN,NaN,1.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,1.00,NaN,1.00,NaN,2.00,1.00,1.00,NaN,1.00,NaN,NaN,NaN,16.00,4.00,NaN,13.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,3.00,NaN,6.00,NaN,1.00,4.00,7.00,NaN,NaN,NaN,NaN,NaN,NaN,3.00,NaN,NaN,5.00,NaN,2.00,1.00,NaN,9.00,NaN,9.00,NaN,NaN,NaN,NaN,2.00,NaN,NaN,1.00,86.00,NaN,6.00,47.00,NaN,NaN,1.00,1.00,NaN,4.00,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,2.00,NaN,NaN,24.00,NaN,NaN,NaN,NaN,2.00,NaN,14.00,NaN,NaN,1.00,NaN,6.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,7.00,11.00,NaN,1.00,7.00,NaN,NaN,NaN,NaN,2.00,63.00,NaN,NaN,NaN,1.00,8.00,15.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,7.00,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,3.00,5.00,2.00,1.00,1.00,1.00,1.00,1.00,1.00,2.00,1.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MINAS Y ENERGIA,274.00,4.00,2.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,1.00,6.00,5.00,2.00,44.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.00,NaN,1.00,NaN,NaN,NaN,1.00,3.00,NaN,26.00,8.00,NaN,NaN,5.00,NaN,NaN,NaN,12.00,NaN,NaN,37.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.00,NaN,1.00,NaN,NaN,1.00,NaN,NaN,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,5.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,2.00,1.00,1.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OTRO,"3,142.00",181.00,63.00,NaN,114.00,33.00,3.00,NaN,54.00,1.00,11.00,64.00,15.00,3.00,16.00,6.00,12.00,2.00,2.00,NaN,10.00,6.00,55.00,78.00,"4,199.00",NaN,27.00,125.00,12.00,223.00,9.00,20.00,67.00,243.00,151.00,4.00,1.00,1.00,89.00,279.00,4.00,72.00,6.00,1.00,7.00,82.00,NaN,NaN,NaN,"1,787.00",11.00,70.00,"1,080.00",3.00,NaN,NaN,NaN,1.00,NaN,NaN,3.00,27.00,NaN,2.00,21.00,1.00,NaN,NaN,NaN,NaN,3.00,5.00,NaN,4.00,NaN,1.00,1.00,NaN,7.00,NaN,NaN,3.00,NaN,NaN,8.00,NaN,14.00,6.00,NaN,NaN,2.00,2.00,NaN,4.00,NaN,NaN,NaN,NaN,4.00,NaN,NaN,1.00,NaN,NaN,NaN,5.00,NaN,3.00,1.00,2.00,1.00,5.00,1.00,1.00,13.00,1.00,NaN,1.00,1.00,3.00,4.00,NaN,13.00,NaN,1.00,NaN,1.00,NaN,NaN,1.00,6.00,NaN,5.00,5.00,NaN,1.00,NaN,NaN,10.00,1.00,3.00,2.00,1.00,NaN,3.00,1.00,NaN,NaN,NaN,18.00,NaN,NaN,13.00,1.00,4.00,NaN,NaN,7.00,NaN,36.00,NaN,NaN,NaN,1.00,1.00,NaN,NaN,NaN,264.00,NaN,74.00,71.00,2.00,3.00,27.00,NaN,NaN,1.00,1.00,27.00,1.00,NaN,NaN,1.00,1.00,3.00,1.00,NaN,NaN,2.00,NaN,NaN,NaN,8.00,2.00,NaN,NaN,37.00,NaN,NaN,NaN,2.00,4.00,NaN,10.00,NaN,NaN,NaN,NaN,2.00,1.00,1.00,1.00,NaN,NaN,NaN,1.00,NaN,3.00,NaN,NaN,2.00,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,13.00,1.00,13.00,11.00,1.00,NaN,16.00,NaN,NaN,NaN,NaN,17.00,54.00,6.00,NaN,NaN,5.00,6.00,33.00,1.00,1.00,NaN,7.00,1.00,NaN,1.00,30.00,NaN,NaN,NaN,NaN,NaN,2.00,NaN,2.00,NaN,NaN,1.00,6.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,20.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2.00,NaN,1.00,NaN,NaN,NaN,1.00,NaN,NaN,NaN,2.00,4.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,3.00,1.00,1.00,2.00,1.00,1.00,2.00,1.00,1.00,2.00,2.00,1.00,1.00,1.00,1.00,1.00,7.00,1.00,1.00,1.00,2.00,1.00,2.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RESIDENCIAL,"7,734.00",129.00,105.00,NaN,642.00,31.00,NaN,NaN,21.00,NaN,44.00,197.00,3.00,NaN,41.00,14.00,38.00,NaN,3.00,10.00,23.00,66.00,111.00,368.00,"2,129.00",NaN,6.00,69.00,6.00,360.00,1.00,3.00,71.00,77.00,92.00,NaN,NaN,NaN,101.00,348.00,NaN,773.00,7.00,12.00,2.00,179.00,NaN,NaN,NaN,"1,502.00",3.00,18.00,186.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168.00,NaN,1.00,45.00,NaN,NaN,NaN,NaN,1.00,NaN,11.00,NaN,NaN,NaN,NaN,NaN,NaN,10.00,NaN,7.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,3.00,NaN,NaN,NaN,NaN,10.00,NaN,6.00,NaN,1.00,NaN,113.00,NaN,NaN,51.00,14.00,NaN,NaN,12.00,95.00,11.00,1.00,5.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,6.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,NaN,NaN,5.00,NaN,18.00,NaN,NaN,15.00,NaN,1.00,NaN,NaN,1.00,1.00,NaN,NaN,NaN,27.00,NaN,8.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,39.00,NaN,19.00,38.00,NaN,NaN,3.00,NaN,NaN,8.00,NaN,63.00,NaN,12.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,NaN,NaN,27.00,NaN,NaN,NaN,2.00,2.00,NaN,190.00,3.00,6.00,NaN,1.00,75.00,NaN,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.00,NaN,NaN,NaN,4.00,NaN,NaN,NaN,1.00,NaN,NaN,NaN,1.00,4.00,5.00,NaN,NaN,29.00,NaN,NaN,1.00,NaN,NaN,7.00,NaN,NaN,NaN,NaN,NaN,22.00,NaN,NaN,NaN,9.00,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,NaN,9.00,1.00,5.00,NaN,NaN,NaN,NaN,NaN,NaN,13.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,2.00,1.00,3.00,2.00,4.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_Contratos2.groupby(['TIPO_SERVICIO', 'SECTOR_CLIENTE_DESC']).size().unstack()

SECTOR_CLIENTE_DESC,AGRICOLA Y GANADERO,COMERCIAL,EDUCATIVO,FINANCIERO,GOBIERNO,INDUSTRIAL,MINAS Y ENERGIA,OTRO,RESIDENCIAL,SERVICIOS,TRANSPORTES,VIGILANCIA
TIPO_SERVICIO,,,,,,,,,,,,
Cooperativa de Vigilancia y Seguridad Privada,16.00,"1,834.00",98.00,49.00,84.00,164.00,3.00,353.00,"4,463.00",228.00,37.00,140.00
Departamento de Seguridad Persona Jurídica,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Empresa Arrendadora de Vehículos Blindados,12.00,"3,017.00",NaN,47.00,338.00,47.00,60.00,343.00,1.00,416.00,526.00,"4,851.00"
"Empresa Asesora, Consultora e Investigadora en Vigilancia y Seguridad Privada",1.00,5.00,4.00,6.00,1.00,NaN,4.00,25.00,NaN,7.00,2.00,NaN
Empresa Blindadora,35.00,291.00,10.00,235.00,23.00,100.00,80.00,350.00,17.00,119.00,33.00,406.00
Empresa de Transporte de Valores,1.00,297.00,3.00,230.00,13.00,3.00,62.00,100.00,NaN,353.00,34.00,2.00
Empresa de Vigilancia y Seguridad Privadas con Armas,244.00,"15,435.00","1,271.00",521.00,"1,293.00","3,403.00",312.00,"4,693.00","12,098.00","4,656.00",502.00,492.00
Empresa de Vigilancia y Seguridad Privadas sin Armas,52.00,"17,151.00",523.00,275.00,66.00,706.00,15.00,"8,359.00","2,062.00","3,426.00",309.00,529.00
"Inscripción en el Registro de Fabricantes, Importadores, Comercializadores, Arrendadores e Instaladores de Equipos para la Vigilancia y la Seguridad Privada",NaN,480.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,9.00

In [ ]:
df_Contratos2.groupby(['TIPO_SERVICIO', 'año']).size().unstack()

In [ ]:
df_Contratos2.groupby(['SECTOR_CLIENTE_DESC',  'año']).size().unstack()

In [ ]:
df_Contratos2.groupby(['ID_CIUDAD', 'año']).size().unstack()

In [ ]:
df_Contratos2.groupby(['ID_DEPARTAMENTO1', 'año']).size().unstack()

In [ ]:
# Para sacar porcentajes se puede usar 
value_counts(normalize=True)

# Step 6: Exploracion de Clientes

In [ ]:
 clientes_df['numero_identificacion'].value_counts().head()

0000000000000    262990
830111257          1474
900276962          1022
890903938           854
860002964           809
Name: numero_identificacion, dtype: int64

In [ ]:
clientes_df.loc[clientes_df['numero_identificacion'] == '800001520', 'ultimo_ano_renovado'].value_counts()

2,022.00    241
0.00        107
2,017.00     12
2,019.00     10
2,018.00      9
2,020.00      9
2,012.00      5
2,014.00      4
2,015.00      4
2,021.00      3
Name: ultimo_ano_renovado, dtype: int64

## Considerar solo clientes activos en el RUES

In [ ]:
clientes_df.loc[(clientes_df['numero_identificacion'] == '800001520') & (clientes_df['ultimo_ano_renovado'] == 2022), 'estado_matricula'].value_counts()

ACTIVA    241
Name: estado_matricula, dtype: int64

In [ ]:
clientes_df = clientes_df[clientes_df['ultimo_ano_renovado'] == 2022]
clientes_df.shape

(85982, 22)

In [ ]:
# Ahora veamos las secciones por ciudades:
clientes_df[clientes_df['camara_comercio'].isin(ciudades_clientes)].groupby(['ciuu_seccion_desc', 'camara_comercio']).size().unstack()

camara_comercio,ABURRA SUR,ARMENIA,BARRANCABERMEJA,BARRANQUILLA,BOGOTA,BUCARAMANGA,CALI,IBAGUE,MEDELLIN PARA ANTIOQUIA,PEREIRA
ciuu_seccion_desc,,,,,,,,,,
"ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN",149.00,256.00,50.00,50.00,"1,638.00",121.00,113.00,181.00,301.00,258.00
ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL,105.00,61.00,30.00,348.00,763.00,213.00,455.00,103.00,573.00,98.00
ACTIVIDADES DE ORGANIZACIONES Y ENTIDADES EXTRATERRITORIALES,NaN,1.00,NaN,7.00,NaN,NaN,NaN,2.00,71.00,NaN
ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO,81.00,51.00,22.00,213.00,586.00,176.00,299.00,75.00,431.00,94.00
ACTIVIDADES FINANCIERAS Y DE SEGUROS,118.00,106.00,61.00,296.00,"1,656.00",421.00,464.00,117.00,642.00,155.00
ACTIVIDADES INMOBILIARIAS,60.00,3.00,3.00,80.00,213.00,45.00,132.00,15.00,248.00,15.00
"ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS",52.00,11.00,14.00,124.00,249.00,100.00,210.00,25.00,328.00,42.00
ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA,4.00,9.00,4.00,24.00,97.00,21.00,22.00,7.00,22.00,8.00
"AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA",14.00,3.00,7.00,51.00,95.00,53.00,53.00,12.00,73.00,2.00
ALOJAMIENTO Y SERVICIOS DE COMIDA,179.00,68.00,11.00,302.00,"1,919.00",239.00,462.00,100.00,873.00,104.00
COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS,"1,393.00",472.00,218.00,"2,320.00","8,241.00","1,872.00","3,380.00",760.00,"5,322.00",872.00
CONSTRUCCIÓN,73.00,17.00,7.00,129.00,101.00,123.00,151.00,41.00,264.00,19.00
"DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO AMBIENTAL",3.00,4.00,2.00,26.00,17.00,11.00,15.00,5.00,22.00,1.00
EDUCACIÓN,37.00,8.00,11.00,52.00,258.00,44.00,93.00,19.00,135.00,24.00
EXPLOTACIÓN DE MINAS Y CANTERAS,1.00,NaN,1.00,12.00,21.00,13.00,4.00,3.00,29.00,1.00
INDUSTRIAS MANUFACTURERAS,597.00,101.00,36.00,431.00,"1,667.00",346.00,824.00,139.00,"1,498.00",117.00
INFORMACIÓN Y COMUNICACIONES,31.00,22.00,4.00,98.00,282.00,73.00,134.00,23.00,187.00,30.00
OTRAS ACTIVIDADES DE SERVICIOS,27.00,25.00,8.00,41.00,140.00,51.00,89.00,31.00,184.00,38.00
"SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO",1.00,7.00,3.00,5.00,32.00,17.00,8.00,4.00,10.00,5.00
TRANSPORTE Y ALMACENAMIENTO,158.00,57.00,45.00,368.00,952.00,250.00,368.00,72.00,450.00,93.00

In [ ]:
clientes_df2 = clientes_df.drop_duplicates(subset=['razon_social', 'nit_propietario'], keep='first', ignore_index=True)
clientes_df2.shape

(83042, 22)

In [ ]:
# Ahora veamos las secciones por ciudades:
clientes_df2[clientes_df2['camara_comercio'].isin(ciudades_clientes)].groupby(['ciuu_seccion_desc', 'camara_comercio']).size().unstack()

camara_comercio,ABURRA SUR,ARMENIA,BARRANCABERMEJA,BARRANQUILLA,BOGOTA,BUCARAMANGA,CALI,IBAGUE,MEDELLIN PARA ANTIOQUIA,PEREIRA
ciuu_seccion_desc,,,,,,,,,,
"ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN",149.00,256.00,49.00,49.00,"1,636.00",120.00,111.00,179.00,300.00,258.00
ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL,102.00,60.00,28.00,348.00,759.00,209.00,450.00,102.00,570.00,95.00
ACTIVIDADES DE ORGANIZACIONES Y ENTIDADES EXTRATERRITORIALES,NaN,1.00,NaN,7.00,NaN,NaN,NaN,2.00,70.00,NaN
ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO,79.00,49.00,18.00,211.00,573.00,158.00,268.00,65.00,385.00,70.00
ACTIVIDADES FINANCIERAS Y DE SEGUROS,117.00,102.00,55.00,291.00,"1,645.00",393.00,436.00,103.00,615.00,135.00
ACTIVIDADES INMOBILIARIAS,58.00,3.00,3.00,80.00,210.00,43.00,132.00,15.00,246.00,15.00
"ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS",52.00,10.00,14.00,124.00,246.00,96.00,203.00,24.00,320.00,33.00
ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA,4.00,7.00,2.00,23.00,95.00,17.00,19.00,4.00,18.00,5.00
"AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA",13.00,3.00,7.00,50.00,94.00,52.00,53.00,11.00,69.00,2.00
ALOJAMIENTO Y SERVICIOS DE COMIDA,178.00,67.00,11.00,302.00,"1,917.00",239.00,461.00,99.00,872.00,102.00
COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS,"1,371.00",464.00,214.00,"2,312.00","8,192.00","1,805.00","3,293.00",727.00,"5,223.00",826.00
CONSTRUCCIÓN,73.00,17.00,7.00,129.00,100.00,120.00,146.00,39.00,262.00,16.00
"DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO AMBIENTAL",3.00,4.00,2.00,26.00,17.00,11.00,15.00,5.00,22.00,1.00
EDUCACIÓN,35.00,8.00,11.00,52.00,256.00,44.00,90.00,18.00,131.00,20.00
EXPLOTACIÓN DE MINAS Y CANTERAS,1.00,NaN,1.00,12.00,21.00,13.00,4.00,3.00,29.00,1.00
INDUSTRIAS MANUFACTURERAS,590.00,101.00,33.00,429.00,"1,662.00",339.00,810.00,132.00,"1,487.00",109.00
INFORMACIÓN Y COMUNICACIONES,31.00,22.00,3.00,98.00,277.00,67.00,129.00,21.00,178.00,26.00
OTRAS ACTIVIDADES DE SERVICIOS,25.00,25.00,8.00,40.00,139.00,49.00,86.00,30.00,182.00,38.00
"SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO",1.00,7.00,3.00,5.00,32.00,17.00,7.00,4.00,10.00,5.00
TRANSPORTE Y ALMACENAMIENTO,155.00,51.00,40.00,365.00,934.00,231.00,317.00,62.00,428.00,69.00

In [ ]:
clientes_df3 = clientes_df.drop_duplicates(subset=['nit_propietario'], keep='first', ignore_index=True)
clientes_df3.shape

(23644, 22)

In [ ]:
# Ahora veamos las secciones por ciudades:
clientes_df3[clientes_df3['camara_comercio'].isin(ciudades_clientes)].groupby(['ciuu_seccion_desc', 'camara_comercio']).size().unstack()

camara_comercio,ABURRA SUR,ARMENIA,BARRANCABERMEJA,BARRANQUILLA,BOGOTA,BUCARAMANGA,CALI,IBAGUE,MEDELLIN PARA ANTIOQUIA,PEREIRA
ciuu_seccion_desc,,,,,,,,,,
"ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN",15.00,7.00,3.00,22.00,84.00,16.00,32.00,7.00,79.00,11.00
ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL,31.00,26.00,9.00,171.00,184.00,59.00,163.00,46.00,180.00,27.00
ACTIVIDADES DE ORGANIZACIONES Y ENTIDADES EXTRATERRITORIALES,NaN,NaN,NaN,5.00,NaN,NaN,NaN,NaN,65.00,NaN
ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO,45.00,22.00,7.00,146.00,203.00,35.00,101.00,20.00,129.00,11.00
ACTIVIDADES FINANCIERAS Y DE SEGUROS,35.00,29.00,6.00,71.00,63.00,32.00,50.00,8.00,77.00,3.00
ACTIVIDADES INMOBILIARIAS,40.00,1.00,3.00,74.00,86.00,25.00,104.00,14.00,190.00,13.00
"ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS",44.00,6.00,10.00,105.00,150.00,55.00,151.00,18.00,253.00,22.00
ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA,2.00,4.00,NaN,3.00,4.00,1.00,2.00,1.00,3.00,NaN
"AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA",9.00,2.00,2.00,17.00,30.00,9.00,42.00,7.00,49.00,1.00
ALOJAMIENTO Y SERVICIOS DE COMIDA,70.00,31.00,7.00,91.00,252.00,58.00,130.00,44.00,286.00,48.00
COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS,560.00,142.00,52.00,919.00,"1,842.00",371.00,921.00,277.00,"2,029.00",197.00
CONSTRUCCIÓN,65.00,14.00,6.00,120.00,81.00,87.00,130.00,31.00,246.00,11.00
"DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO AMBIENTAL",3.00,2.00,1.00,9.00,9.00,6.00,10.00,3.00,20.00,1.00
EDUCACIÓN,28.00,7.00,10.00,37.00,113.00,22.00,59.00,10.00,84.00,10.00
EXPLOTACIÓN DE MINAS Y CANTERAS,1.00,NaN,1.00,10.00,16.00,10.00,4.00,3.00,27.00,1.00
INDUSTRIAS MANUFACTURERAS,438.00,33.00,13.00,287.00,626.00,159.00,431.00,74.00,930.00,44.00
INFORMACIÓN Y COMUNICACIONES,21.00,10.00,1.00,41.00,75.00,21.00,58.00,7.00,106.00,7.00
OTRAS ACTIVIDADES DE SERVICIOS,17.00,11.00,6.00,38.00,79.00,22.00,55.00,17.00,89.00,13.00
"SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO",1.00,1.00,2.00,5.00,12.00,5.00,4.00,2.00,4.00,1.00
TRANSPORTE Y ALMACENAMIENTO,77.00,19.00,13.00,206.00,198.00,44.00,76.00,17.00,115.00,12.00